### ISSUE TITLE
condition.string.preg argument "as" missing

### ISSUE THREAD

**Issue by hacksch** [FluidTYPO3/vhs#1009]
I miss the argument "as" in the viewhelper declaration.
In line 101 the argument will be used. But its not possible to set them without declaration in method initializeArguments.

**Comment by bjo3rnf** [comment]
Hi Martin,

this is actually some special case. ``as`` should be registered with TemplateVariableViewHelperTrait::registerAsArgument() which is missing here but unfortunately the use case of the as argument is different to the other viewhelpers as it should contain the matches instead of the viewhelper content. Thus the trait can't be implemented like this. I'll have a look at it.

Cheers
Björn

**Comment by bjo3rnf** [comment]
To quote @NamelessCoder:

> "fixed" by refactoring the preg-related ViewHelpers to two proper scopes - see #1023. Thanks for bringing this to our attention!
