### ISSUE TITLE
Trim for v:variable.set and v:variable.register.set

### ISSUE THREAD

**Issue by neufeind** [FluidTYPO3/vhs#1036]
Provide an optional parameter "trim" to easily strip whitespaces from generated content. For cases like
`<v:variable.set` name="myContent">``<f:render partial="..." />``</v:variable.set>`
easily some whitespaces around end up in the variable.

Workaround for now, after setting the variable:
`{v:format.trim(content: myContent) -> v:variable.set(name: 'myContent')}`

**Comment by NamelessCoder** [comment]
We chose not to provide that since `trim` would only apply to strings and `v:variable.set` allows setting any type of variable. So to avoid having X number of variables that only apply to one type of variable being set, it would be much better to recommend the inline syntax which can also be used for `f:render`, `f:for` and even `f:if`:

```xml
{f:render(section: 'MySection') -> v:variable.set(name: 'myvariable')}
{f:render(section: 'MySection') -> v:variable.set(name: 'myvariable') -> v:if(condition: onlyifthisistrue)}
{f:for(each: allobjects, as: 'object') -> v:variable.set(name: 'allhtml')}
```

This syntax eliminates every whitespace normally caused by adding conditions and such. On a side note, from TYPO3v8 and onward, `f:spaceless` can be used to control whitespace trimming (and can also be used with inline syntax to trim just a single section's output). So I would say no to this feature and hope you agree with the reason and alternative suggestion ;)

**Comment by neufeind** [comment]
Thanks for the reasons given, agreed.
