### ISSUE TITLE
[FEATURE] TYPO3 ContentRepository

### ISSUE THREAD

**Issue by danielkestler** [FluidTYPO3/vhs#1048]
Suggested feature: implement an Extbase ContentRepository to handle all content fetching, get rid of manual exec_SELECTquery calls. Would be less error prone than the current way. What do you think?

**Comment by cedricziel** [comment]
Hi Daniel,

thanks for your suggestion - very appreciated!

But we won't implement it - at least not the way you suggested it. Extbase itself abstracts over `exec_SELECTquery` and needs to be booted within every content element. Extbase persistence itself is quite a performance hogger + there's no mechanism for custom fields which would make a ContentRepository (where the repository part correspondents to a extbase domain repository) pretty useless after all.

The problem here is that building CONTENT cObjects is a very fragile process with many variables. - That's why I think the core should implement anything like that - if anybody should.

Cheers,
Cedric

**Comment by danielkestler** [comment]
Hi Cedric, thanks for your quick reply. I absolutely understand your point. Maybe then a custom Utility class might be a solution to get SQL queries out of the ViewHelpers (I think they don't belong in there)?

**Comment by cedricziel** [comment]
We'll take absolutely every PR into consideration  we'll receive about that topic :)

**Comment by NamelessCoder** [comment]
I should add here that work is taking place in the TYPO3 core to replace the old DatabaseConnection with Doctrine - something that would at least allow us to more closely *emulate* the way various repositories which are normally Extbase dependent, would select records. Since our implementations don't deal with domain objects for content (there's a much longer story behind this that I'm happy to tell you over Skype for example, but it's a bit more than I have time to type right now ;)), as Cedric says we hesitate a lot to "force" Extbase on this - at least for the time being (read: until TYPO3 finds a way to consistently deliver content/pages as domain objects and cObjects become aware of those).
