### ISSUE TITLE
[BUG] v:render.uncache does not work in 7.6.9

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/vhs#1053]
The problem is that the ViewHelper tries to serialize the controller context, which contains a closure and thus is not serializable.

**Comment by NamelessCoder** [comment]
Hi Jost,

This only happens if you pass all arguments or an argument that contains a reference to an object with closures, as `arguments` to `v:render.uncache`. Avoid using `{_all}` and be careful which objects you pass, then you'll be safe.

**Comment by JostBaron** [comment]
No, this happens every time, even on ViewHelpers without any arguments. It starts to "work" (i.e. failing at a later point) if you comment out [line 61](https://github.com/FluidTYPO3/vhs/blob/2.4.0/Classes/ViewHelpers/Render/UncacheViewHelper.php#L61). The problem is the controller context - it references nearly every object that exists in TYPO3, since it references the object manager.

**Comment by NamelessCoder** [comment]
I checked and couldn't find any recent changes in TYPO3 that would put a closure on a property of any object normally found in the hierarchy starting from ControllerContext. If one or more related classes now truly do contain closures then the only suggestion I can make is to implement `__sleep` on those objects (in the TYPO3 core) to avoid returning the closures.

I'm not entirely sure but I would almost expect that if anything broke serialization of the controller context then that same change would have broken widgets which also depend on a serialized context. I'm thinking if you use an AJAX widget in that same template it too will break in the same way.

You are absolutely sure that this isn't because you assign a closure somewhere in request or response parameters? If you can locate the cause for this closure being in this scope where it shouldn't be, perhaps I can point to where a patch could be made or a workaround - but I'm afraid we can't make `v:render.uncache` work without serializing the controller context which is absolutely vital for the deferred rendering to happen correctly. Manually freezing/thawing all required values is not really feasible either (would simply break again if any change happened in ControllerContext properties).
