### ISSUE TITLE
v:page.menu login restricted access

### ISSUE THREAD

**Issue by 7elix** [FluidTYPO3/vhs#1062]
Hi team,

seems I have a strange behavior for v:page.menu.

`<v:page.menu as="navigation" pageUid="{settings.pids.primary}" entryLevel="1">`
`								<f:for each="{navigation}" as="item">`
`									<li>`
`										<f:link.typolink parameter="{item.uid}">`
`											{item.title}`
`										</f:link.typolink>`
`									</li>`
`								</f:for>`
`							</v:page.menu>`

vs. 

`page.100 = HMENU`
`page.100.entryLevel = 1`
`page.100.1 = TMENU`
`page.100.1.NO = 1`

for pages with access mode hide/show on login.
The issue is cause by my tsfe fe_user settings although not logged in.

**Comment by 7elix** [comment]
fixed on master already.
could be fixed with additional cast in page service for groupData['uid']

        if (TRUE === is_array($GLOBALS['TSFE']->fe_user->user)
			|| (TRUE === isset($GLOBALS['TSFE']->fe_user->groupData['uid']) && 0 < (int) $GLOBALS['TSFE']->fe_user->groupData['uid']))

**Comment by 7elix** [comment]
Should I send a path for master / 2.4.1?

**Comment by NamelessCoder** [comment]
TER version 3.0.0 will be released soon - and it will contain all commits from `development` so that should fix the issue.

We may need the patch for the `legacy` branch though, so if you would prepare a bug fix based on and targeted at that branch, that would be appreciated!

But I don't quite see how casting to integer solves the issue *unless* it's because the data type in that variable is some type that `0 < $varWithType` is FALSE but `(integer) $varWithType` yields an integer above 0. It could be that `groupData['uid']` is actually a CSV string with commas in the front position (e.g. `,1,2`) - in which case we need to check if `GeneralUtility::trimExplode(',', $csv)` returns an array with at least one above-zero integer value, or the VH would see the page incorrectly as "not protected".

**Comment by NamelessCoder** [comment]
Closed along with https://github.com/FluidTYPO3/vhs/issues/1063
