### ISSUE TITLE
composer.json: require php version not correct

### ISSUE THREAD

**Issue by mfell** [FluidTYPO3/vhs#1064]
"php": ">=5.4.0"

-> no installation (composer) with php 7 possible

**Comment by NamelessCoder** [comment]
Are you sure about that? The notation should allow any version *above* 5.4.0. Expect that to increase to requiring 5.5 any day now since 5.4 is unsupported - but using 7.0.x should absolutely be possible!

**Comment by mfell** [comment]
This is the answer from composer:

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - typo3-ter/vhs 2.4.0 requires php >= 5.4.0, <= 5.6.99 -> your PHP version (7.0.6) does not satisfy that requirement.

The notiation might be wrong ... but I agree with you, it looks correct.
https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators

Maybe somthing like this cound work:
... >=5.4.0 || >=7.0.0

**Comment by NamelessCoder** [comment]
You're using `typo3-ter` which means you use the TYPO3 composer repository - that may be adding `ext_emconf.php` constraints that do not exist in the vanilla composer.json that belongs to this version (https://github.com/FluidTYPO3/vhs/blob/2.4.0/composer.json). To avoid that, install using `fluidtypo3/vhs`. Or add `--ignore-platform-deps` to your `composer install` or `composer update` commands. Yes, it is a mistake that the max PHP version is set in VHS 2.4.0 since it is compatible with PHP7. However, we won't be making further releases in the 2.4 branch (and this restriction does not seem to apply in EM itself if you installed via packagist composer, e.g. name `fluidtypo3/vhs`).

Generally speaking I don't encourage using the TYPO3 composer repository (for this and other reasons) when the same package exists in packagist which all FluidTYPO3 packages do.

The next release of VHS (3.0.0) will be officially compatible with PHP7 also according to `ext_emconf.php` metadata.
