### ISSUE TITLE
v:asset.script lacks the integrity attribute

### ISSUE THREAD

**Issue by dj-rabel** [FluidTYPO3/vhs#1089]
In TYPO3 8, they added the possibility to add a checksum for the HTML5 integrity attribute.
https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Page/Index.html#includejs-array
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

It would be very nice, if we could have this attribute also at least at the StyleViewHelper.
Maybe in addition, there could be a automatic generation flag so we don't have to add it manually or evan for the automatic generated vhs-assets file...

**Comment by NamelessCoder** [comment]
We could implement this into the automatically generated script tags - but we could not implement it in a way that allows you to consistently define this manually in the ViewHelper itself (since assets are not defined 1:1 to `<script>` and `<link>/<style>` tags and the VH arguments all concern the asset itself, not the tag that will be used to load it).

Thanks for bringing it up :)

**Comment by 4-lom** [comment]
Your welcome.

I think, I've done a nice implementation of that feature allready in my fork. I'm going to test and commit it later this day.
Weather it works or not, i will write back then and eventually create a pull request for this feature.

**Comment by 4-lom** [comment]
Ok, it's done. Hope u will like it 👍

**Comment by InvisibleKind** [comment]
I'm curious if auto-generation of an integrity hash will not make a security leak. Bcs the idea of SRI is, that browser needs to verify the provided hash, and if browser's calculation doesn't match the data provided by script-tag, the js-file is refused and not executed.

So, in case file on CDN was replaced with some credit-card-sniffer, the hash will be different.
But in case of auto-generated hash it will be generated for sniffer as well and will be correct form browser's point of view.

Please, correct me if I'm wrong.

**Comment by cedricziel** [comment]
You're absolutely correct, @InvisibleKind . Yet this would take us half-way and at least make sort of a "transport-guarantee".

**Comment by NamelessCoder** [comment]
The SRI should only be possible for local resources - anything else would be a security issue and if that's the case we need a fix. For remote resources you do need to specify this manually (and not use `v:asset.script` to create the tag since those don't support manual SRI for exactly that reason.

If someone would check if we're okay security wise that would be appreciated. I'm a little short on time.

**Comment by NamelessCoder** [comment]
Solved, but wasn't closed along with merging the PR.
