### ISSUE TITLE
Support of cropping in <v:media.image />

### ISSUE THREAD

**Issue by georgringer** [FluidTYPO3/vhs#1090]
The viewhelper `<v:media.image />` does not yet support the cropping. 
In `AbstractImageViewHelper` cropping must be addded.

I will come up with a patch

**Comment by bjo3rnf** [comment]
Closed by #1091

**Comment by ursbraem** [comment]
thanks a lot for that patch!

**Comment by Bjoelin** [comment]
Hey folks, sorry for posting in this closed issue. 

I just noticed that <v:media.image.width> and <v:media.image.height> viewhelpers both return the original file's dimension thus ignoring cropping as well. 

Since they extend a different class (AbstractImageInfoViewHelper) is there a way to port this patch to the width/height viewhelper?

**Comment by NamelessCoder** [comment]
@Bjoelin The width and height ViewHelpers operate on a fixed resource. If you need to get the width and height of an already scaled image you need to assign your rescaled image URI as a template variable and pass that into the width/height ViewHelpers.

Essentially: they are for **reading**, not for **writing** and must not cause any image processing to occur. This will not be ported.

**Comment by Bjoelin** [comment]
@NamelessCoder thanks for your feedback; this approach is gold : - )

**Comment by luzat** [comment]
@Bjoelin I'm late, but this works:

    {f:uri.image(image: file, maxWidth: '1200') -> v:format.pregReplace(pattern: '-^/-', replacement: '') -> v:variable.set(name: 'bigImage')}

The path needs to be relative (e.g. `fileadmin/...` instead of `/fileadmin/...`) for `GeneralUtility::getFileAbsFileName` in **AbstractImageInfoViewHelper.php** to work.
