### ISSUE TITLE
additionalAttributes broken in Typo3 8.2.1

### ISSUE THREAD

**Issue by misterboe** [FluidTYPO3/vhs#1100]
Error:

```
Undeclared arguments passed to ViewHelper FluidTYPO3\Vhs\ViewHelpers\Page\Header\LinkViewHelper: additionalAttributes 
```

Code: 

```
<v:page.header.link additionalAttributes="{sizes: '57x57'}" rel="apple-touch-icon-precomposed" href="{icon57}"/>
```

**Comment by misterboe** [comment]
@xf- this was the reason for my PR. I thought that "additionalAttributes" was removed. But it seems to be a Bug

**Comment by bjo3rnf** [comment]
The problem is: all viewhelpers that extend `AbstractTagBasedViewHelper` require calling `    parent::initializeArguments();` in TYPO3 8 since the registration of `additionalArguments` has been refactored away from the constructor...

**Comment by 4-lom** [comment]
I think the problem is, that the new package `TYPO3Fluid.Fluid` provides in the `AbstractTagBasedViewHelper` a new method called `validateAdditionalArguments`. The default implementation of this function is causing an error if u pass at least something else than an empty array.

`@see \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->validateAdditionalArguments`

To fix this we could, as the easies solution, overwrite this method with an empty one or return true, in all ViewHelpers that should provide the `additionalAttributes` functionality.

Maybe we could also implement a simple check against the html specs here. Like "is this attribute valid on the desired html tag". I have a xsd validation solution in mind... or something like that ^^

**Comment by NamelessCoder** [comment]
@4-lom The AbstractTagBasedViewHelper method you mention is responsible (in the standalone package) for validating additional arguments which were not declared with `registerArgument`. In the default implementation it allows any `data-` prefixed argument to be passed.

To my knowledge there should be no issue using `additionalAttributes` on CMS tag based ViewHelpers nor standalone Fluid ViewHelpers (as that functionality is a core one; and as you noticed it is there to support custom attributes that are *not* `data-` prefixed).

@bjo3rnf I think has the problem nailed down and VHS itself also has a goal to move every argument away from render methods.

On a side note: render method arguments are expected to be deprecated since they are far less efficient than using `registerArgument` (requires an additional layer of both reflection and ViewHelper invocation).

We may be able to make a temporary fix by implementing `initializeArguments` on those ViewHelpers which are affected and if necessary do a version check to add the missing ones - this would be the first step to moving render method arguments away anyway so there's no wasted work. I'm not sure if it would work in the Trait but it would be worth a try!
