### ISSUE TITLE
v:iterator.explode does not work with "as"

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/vhs#1254]
Example:
`<v:iterator.explode content="test 1 2 3" as="parts" glue=" "><f:debug>{parts}</f:debug></v:iterator.explode>`
yields "test 1 2 3" as output, in particular the DebugViewHelper is never called.

The cause for this seems to be that ExplodeViewHelper uses the CompileWithContentArgumentAndRenderStatic trait and both the view helper itself and the trait use the "content" argument, but for different purposes. If the "content" argument is supplied, the children rendering closure (as defined by the trait) will return the value of "content" without considering the child elements. But the view helper already uses the "content" argument for specifying the input, not the output, when using "as". When not using "as", everything is fine and works as expected.

**Comment by marvin-martian** [comment]
Can confirm, just hit the same problem.

**Comment by pkerling** [comment]
v:iterator.chunk is also broken (attribute is called "subject" there but the problem is the same).

**Comment by monosize** [comment]
The problem is in `TYPO3Fluid\Fluid\Core\ViewHelper\Traits\ CompileWithContentArgumentAndRenderStatic::buildRenderChildrenClosure`
see https://github.com/TYPO3/Fluid/blob/2.3.0/src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php#L104

I think the method `CompileWithContentArgumentAndRenderStatic`trait is not suitable for the purpose of using an `as`argument.

If the first not required argumentName exists in $arguments then the children aren't rendered.
In this case it's `$arguments['content']` and the children are ignored.

Maybe we need a `CompileWithAsArgumentAndRenderStatic`trait. (or does such a trait already exist?)

**Comment by realJustmike** [comment]
same problem here. had to switch back to vhs 3.1.0 again

**Comment by NamelessCoder** [comment]
Yep, that's the problem - we can't use the content argument VH trait with one that supports "as". If we switch to renderStatic and use the existing VHS trait for template variable handling VH to handle rendering, things should work. Other VH may need the same treatment.

**Comment by mfvetter** [comment]
This is how I was able to have v:iterator.explode and f:for to work together with version 4.0:

`<f:for each="{v:iterator.explode(content: '{myArraywithCommas}', glue: ',')}" as="exploded">
	Hello {exploded}...
</f:for>`

**Comment by Stuffy** [comment]
We also have this bug. The fix from @mfvetter worked tho. So thanks for that.

**Comment by rsternec** [comment]
Had the same problem, switch back to vhs 3.1.0 helps for the moment.

**Comment by C0lumbus** [comment]
You can use this crutch:

`<v:variable.set name="exploded" value="{itemToExplode -> v:iterator.explode(glue: ',')}" />`

BTW, shouldn't the parameter named "glue" be renamed to "delimeter"? It makes more sense, as we exploding string and not gluing array values…
