### ISSUE TITLE
\FluidTYPO3\Vhs\ViewHelpers\IfViewHelper is not working on typo3 8.6.1 in taditional mode (no composer)

### ISSUE THREAD

**Issue by pegle** [FluidTYPO3/vhs#1275]
_Class 'TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\BooleanNode' not found 

Error thrown in file
/var/www/hosts/project/public/typo3conf/ext/vhs/Classes/ViewHelpers/IfViewHelper.php in line 113._

In typo3 8.6.1 exists a class named \TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\BooleanNode, but there is no method named "evaluateComparator"

**Comment by cedricziel** [comment]
I've noticed that as well, but eventually migrated away from v:if in favor of f:if since that ohne does support complex boolean conditions now as well, as long, as they're one level deep.

Migration is simple:

```
v:if stack=

# becomes
f:if condition=

```

I do think however, that complex condition stacks with v:if are an anti-pattern and you may want to create specualized condition viewhelpers tailored to your model to make your templates more concise, such as

```
<myExt:model.conference.isUpcoming>
```

Claus can you take a look at the class loading issue?

**Comment by NamelessCoder** [comment]
Closing as "won't fix" - the class truly does not exist on v8 regardless of composer mode or not. The VH itself is deprecated and scheduled for removal and won't be migrated. The tip to use `f:if` is essential; it supports any levels of nested and complex conditions without having to express them as an array.
