### ISSUE TITLE
insert JS assets at end fails if there is are head or body-tags inside js inside content

### ISSUE THREAD

**Issue by EnzephaloN** [FluidTYPO3/vhs#1283]
We have a javascript which generates a popup-page for printing-purposes. The js looks something like this:
`
...
write('<!doctype html><html><head></head>');
write('<body onload="print();" style="font-family: Arial; font-size: 15px;">');
write(text);
write('</body></html>');
...
`
But sadly VHS corrupts this javascript by adding his <script type="text/javascript" src="typo3temp/vhs-assets-pageslidejs.js?1491303894"></script> before the closing body. Also it destroys the first line, because it adds a linebreak between <head> and </head>.

I had to remove the head-tags and I do not close the body-tag, so it works for me for now. But maybe you can rethink your "find the end of the document"-method-stuff.

Thanks.

**Comment by bjo3rnf** [comment]
I'm afraid I don't understand the issue properly. Could you please provide the resulting html source as a gist fx?

**Comment by NamelessCoder** [comment]
@bjo3rnf I can explain. When VHS tries to insert footer tags it does so by matching the closing `</body>` tag. However, it doesn't check if there are multiple such closing tags - and will only insert asserts right before the *first* closing tag it finds. The solution as such should be to change the replacement so we instead find out the string position of the *last* `</body>` tag and split+merge strings extracted by `substr()` with the string of generated assets.

In the example above the current logic fails because IIRC we use `str_replace()` - and this is a bit too naive about things like tags nested in JS inline code (and CDATA, and comments, etc.)

**Comment by NamelessCoder** [comment]
Oh btw @bjo3rnf thank you, and @cedricziel, for the recent maintenance spree ;)

**Comment by EnzephaloN** [comment]
@NamelessCoder Thank you for your explanation. Will you fix this "bit too naive" thing in the next version?

**Comment by bjo3rnf** [comment]
I see. This shouldn't be too hard to fix. I'll have a look.
