### ISSUE TITLE
v:random.string built-in insurance is not working

### ISSUE THREAD

**Issue by topfender** [FluidTYPO3/vhs#1326]
The viewhelper description says there is a "built-in insurance that first character of random string is an alphabetic character", but there isn't.

I'm using 4.2.0

**Comment by NamelessCoder** [comment]
Confirmed - and the docs should be changed to remove that statement. It wouldn't be possible to guarantee this since adding support for defining the list of characters manually (or we'd have to potentially force a character that wasn't in the list). It is however easy enough to manually append a single safe character when you use this VH in an attribute of a tag. Even so, sorry about the confusion!
