### ISSUE TITLE
v:tag condition to print or skip

### ISSUE THREAD

**Issue by Scarbous** [FluidTYPO3/vhs#1347]
It would be nice, if I can add a condition to print or skip the Tag which wrap content.

Maybe I want to add a Link to an Image but in some cases I only want to show the Image without the link.
My code looks like:

```
<f:if condition="{link}">
<f:then>
<v:tag name="a"...>
<v:image src="image" />
</v:tag>
</f:then>
<f:else>
<v:image src="image" />
</f:else>
</f:if>
```

But it can look like:

```
<v:tag name="a" condition="{link}"...>
<v:image src="image" />
</v:tag>
```

**Comment by bjo3rnf** [comment]
Hi Sascha,

I like this idea very much but since the use case is mostly if not always a wrapping link I think it would make more sense to implement this into `v:page.link`. What do you think?

Cheers
Björn

**Comment by bjo3rnf** [comment]
One more thing: I think this can already be achieved with `v:link.typolink` of `f:link.*` which will only render the wrapping link if the resulting URL is valid.

**Comment by Scarbous** [comment]
@bjo3rnf thnak you for your feedback.
Thats right, I can use the `v:link.typolink` but that works only for links.

If no one have simliar szenarios, you can close that issue.

**Comment by NamelessCoder** [comment]
Hi guys,

I'll close this issue but that in my way means that this feature request is forgotten. Instead:

* There's a plan to make TagBuilder behave this exact way if tag name is omitted (so you can dynamically remove the tag and attributes but render the content).
* I've also got a plan to add `f:tag` (more or less copy of `v:tag`) in Fluid and then take advantage of that change in TagBuilder.
* And if all goes well, you should also be able to opt-in to this behavior in your own TagBasedViewHelpers.
* And if it can be done without breaking stuff and gets the approval of the other Fluid maintainers, I'll propose to make this a general argument for all TagBasedViewHelpers so you can control that behavior through template files.

So I'll close it here but keep an eye on Fluid, this is something I think will come soon since tag-ViewHelpers are currently a bit underpowered; can't be compiled, needs special parent class, etc. which can all be improved. Being able to null the tag name should be one of the first new features coming from improving the tag-ViewHelpers!
