### ISSUE TITLE
v:render.uncache 

### ISSUE THREAD

**Issue by stephangrass** [FluidTYPO3/vhs#1370]
Hi,
I use the v:render.uncache viewhelper like the normal working f:render viewhelper but I get the error:

 The Fluid template files "" could not be loaded. (More information)

TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException thrown in file
/Users/stephangrass/Documents/_Webs_/hs-mannheim.de/typo3/typo3_src-8.7.4/vendor/typo3fluid/fluid/src/View/TemplatePaths.php in line 719.

I don't know where to look to resolve this problem. I think that all template paths definitions are set correctly.

**Comment by NyroTheCat** [comment]
I get the same error.

I placed the ViewHelper inside the main typo3 template file (no extension template).

* TYPO3 8.7.6
* VHS 4.3.3

Typoscript
```typoscript
10 = FLUIDTEMPLATE
10 {
  file = fileadmin/templates/Default.html
  partialRootPath = fileadmin/templates/partials/
  layoutRootPath = fileadmin/templates/layouts/
}
```

Fluid Template
```html
<div class="pull-right">
  <v:render.uncache partial="SomePartial"/>
</div>
```

**Comment by NamelessCoder** [comment]
This ViewHelper only works if you provide it with a complete extension context. It will in nearly all cases not work with FLUIDTEMPLATE. The very minimum requirement is an extension as context, which implies you must provide `extensionName`, `vendorName` and possibly others.

Usage of this in FLUIDTEMPLATE however indicates a less than ideal structure. Since you are already rendering this in TS, you have USER_INT objects available and they can contain COA which can render a FLUIDTEMPLATE. This has the exact effect of making your entire FLUIDTEMPLATE object rendering uncached. Unless the FLUIDTEMPLATE you render is absolutely gigantic, this should be a perfectly fine method. Note that this is actually what v:render.uncache does: create a USER_INT that gets rendered.

Alternatively you should consider 1) not storing templates in fileadmin, which is by now considered an anti-pattern exactly because it has no extension context, and 2) creating an actual controller for this that you can register with an uncached controller action.

**Comment by NyroTheCat** [comment]
Thank you for pointing that out! Unfortunately this explicit case is not mentioned in the [docs](https://fluidtypo3.org/viewhelpers/vhs/master/Render/UncacheViewHelper.html). According to the docs, the usage is equal to `f:render`, which works as expected even outside extension context.

I already considered either to use an USER_INT object or a controller and will choose one of those alternatives.

**Comment by medarob** [comment]
This viewhelper does not work for me :/

I use it in a MASK content element.

> <v:render.uncache partial="MyTemplate" arguments="{_all}" />

But I get the following error:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1225709597: The partial files "/var/www/name/typo3conf/ext/mask/Resources/Private/Partials/MyTemplate.html", "/var/www/name/typo3conf/ext/mask/Resources/Private/Partials/MyTemplate" could not be loaded. | TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException thrown in file /var/www/staging/typo3_src-7.6.24/typo3/sysext/fluid/Classes/View/TemplateView.php in line 478.

So, typo3 is looking at the default MASK path for the template file.

However, in the extension configuration for MASK I changed the paths for my MASK CE template files to

> typo3conf/ext/EXTName/Resources/Private/_Mask/maskcontent/

I don't know why the default path was used and not the new one.
Can anyone help me to fix this problem?

Thank you

**Comment by cedricziel** [comment]
(That's a really ugly path, i'd go fix that first)

About your problem: is the path in your partialsRootPaths typoscript option?

**Comment by cedricziel** [comment]
Oh by the way: the above comment by @NamelessCoder is mucho importante!

**Comment by medarob** [comment]
I added the path but I get the same error.

I also read the comment by @NamelessCoder but I did not really understand it, what do I have to change in order to make it work. Can you provide an example?

(Why is this not a good path? For every extension which uses Layouts, Partials and Templates I created subfolders so that all files are well structured in my own extension.)

**Comment by NamelessCoder** [comment]
The extension context is `EXT:mask` therefore it only looks in those paths. Further depending on how this all gets rendered, and how you overrode the template paths, that configuration may not be applied at the execution point where your template is being rendered.

PS: You should upgrade your TYPO3 site. The resolving of these paths is even worse on 7.6 because on that version, it completely depends on the TS or controller init that gets performed, whether or not the paths or even the default paths get added. If you don't tell, Fluid won't know (and this includes specifying view paths *and* extension context for every single FLUIDTEMPLATE you might render). It's far easier to handle on 8.7 because there, TS doesn't need to be as explicit and can make do with just specifying the extension context then configuring TS paths for that ext.

But none if this is, sorry to say, a problem in VHS or anything we can/should attempt to solve there. This particular ViewHelper works this way for a very good reason and shouldn't be used outside of MVC contexts especially given my earlier explanation about `USER_INT`. I'll close the issue.
