### ISSUE TITLE
v:page.languageMenu not generating language menu in TYPO3 8.7

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/vhs#1375]
TYPO3 status messages returns 

> Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /homepages/10/d177621094/htdocs/www/typo3conf/ext/vhs/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php line 291 

The ViewHelper is implemented like this:

`<v:page.languageMenu class="lang" classCurrent="current" defaultLanguageLabel="DE" labelOverwrite="DE,EN" hideNotTranslated="1" />`

Worked fine in 7.6.x, now only DE appears in the frontend with above mentioned error message in the backend.

**Comment by NamelessCoder** [comment]
@MrMooky Could you try if https://github.com/FluidTYPO3/vhs/pull/1366 solves the issue? I'm not sure it takes care of the foreach warning but it should correct the visible languages including translating their labels.

**Comment by MrMooky** [comment]
Applied all changes to the three files, cleared the cache, even de- and reinstalled vhs – now I ended up with `Oops, an error occurred! Code: 201709070740496678fd58` on a white background (no standard TYPO3 error message).

**Comment by MrMooky** [comment]
**Update**: the above was my mistake, apologies. But still, only "DE" is showing up after applying the changes. But it seems the error message in the backend is gone, at least.

**Comment by NamelessCoder** [comment]
Hopefully the list of shown languages now matches the right criteria:

1. The `sys_language` record must exist and be active
2. A translation for each language must be made as "alternative page language" using translation
3. The translation must be active and refer to the language shown in the menu
4. IIRC, one `config.sys_language_uid` section must also exist for each language but I'm not sure if that prevents building the link or just throws an error when you click it.

Since you have `hideNotTranslated="1"` the menu will also not show all languages but only those that are actually translated on the current page. Setting that parameter to "0" should show all your languages - if it doesn't, I would suspect either 1 or 4 from above.

If this doesn't match what you experience it would help a lot with more info, for example your language-handling TS block, which `sys_language` records you have and whether you've got all the expected alternative page languages.

**Comment by MrMooky** [comment]
Still no success. When using `<v:page.languageMenu />` only (no options), it's generating "English" but with a link to language 0, which is German.

![screen shot 2017-09-08 at 8 33 25 am](https://user-images.githubusercontent.com/3603346/30198870-6f3cf638-9470-11e7-962f-0b890c6a6483.png)

The translations of the page (Alternative Page Language) are correct as well:

![screen shot 2017-09-08 at 8 34 05 am](https://user-images.githubusercontent.com/3603346/30198902-8a68bf64-9470-11e7-99ba-86017ec732ed.png)

This is the TS we're using:

```
# Deutsch
config.sys_language_uid = 0
config.language = de
config.sys_language_isocode_default = de
config.locale_all = de_DE.UTF8
config.htmlTag_langKey = de

# English
[globalVar = GP:L = 1]
config.sys_language_uid = 1
config.language = en
config.sys_language_isocode = en
config.locale_all = en_UK.UTF8
config.htmlTag_langKey = en
[global]
```

**Comment by NamelessCoder** [comment]
You may need to set the default language label using VH attributes if the default language isn't English (which by the way it should be if you have multiple languages).

**Comment by MrMooky** [comment]
I'm not quite sure what to apply here then: `<v:page.languageMenu defaultLanguageLabel="DE" labelOverwrite="DE,EN" hideNotTranslated="0" />`

**Comment by NamelessCoder** [comment]
I'm not very experienced with this particular VH, nor with translations, but perhaps `labelOverwrite` is causing some trouble. It could also be related to your TS config - AFAIR you shouldn't use `config.sys_language_uid = 0` anywhere since that would reference a `sys_language` record that doesn't exist.

If that doesn't help I think it's time to call on some of the other maintainers who regularly work with localisation!

**Comment by MrMooky** [comment]
Unfortunately, I was not able to solve this, so downgrading to v4.2.0 was the only option.
