### ISSUE TITLE
v:media.source for retina images

### ISSUE THREAD

**Issue by DanielRuf** [FluidTYPO3/vhs#1386]
How could a working solution look like to deliver normal and retina images from one original file from the backend?

http://brianflove.com/2014/08/07/retina-display-images/

Can we use https://github.com/sitegeist/sms-responsive-images?

**Comment by NamelessCoder** [comment]
`sitegeist/sms-responsive-images` looks pretty good to me and their intro on https://techblog.sitegeist.de/responsive-images-with-typo3-8-7/ should explain the usage. I'd rather not include this in VHS - in fact, I'd rather see this taken over by a dedicated package like that one, due to the non-ViewHelper code layer it requires. From the looks of it, `v:image` and company are outdated after the crop feature was added to TYPO3.

I don't think we'll do much about this, except perhaps to deprecate `v:image` at some point since there's no need to have two packages doing the same thing. So do go check out if that package works (and if you don't mind, drop a word here if it does a good job, so we can start recommending that).

**Comment by DanielRuf** [comment]
Thanks. I think we will evaluate it and let you know how good it works for our setups.

**Comment by blueamerican** [comment]
Isn't the the quality property of v:uri.image that what we search here?

{v:uri.image(src: '{file.uid}', width: 850, quality: 85, treatIdAsReference:1)}

**Comment by DanielRuf** [comment]
> Isn't the the quality property of v:uri.image that what we search here?

No, retina is for x2, x3, x4 pixel density. Do not confuse quality with pixel density.

**Comment by DanielRuf** [comment]
It's basically like this:

- generate picture with 1000x300 px or similar
- set the css width and height to 500x150 px = pd of 2

**Comment by blueamerican** [comment]
i had the requirement for a project to generate the higher pd images with a lower compression.
I thought i wouldn't be possible, but yesterday i saw the quality property of v:uri.image.

**Comment by DanielRuf** [comment]
The quality property is just another compression setting used by imagemagick / graphicsmagic. You can mix the options.

**Comment by DanielRuf** [comment]
Bump.
