### ISSUE TITLE
Suggestion: Render.uncache viewhelper should work in backend context

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/vhs#1409]
Would be fine if the render.uncache viewhelper would work in backend context too.

Uncaught TYPO3 Exception: Call to a member function uniqueHash() on null 
../ViewHelpers/Render/UncacheViewHelper.php in line 66.

because called on TSFE object which is not available.

Needed in BE-modules as other viewhelper gets cached (like extension.loaded for example).

**Comment by NamelessCoder** [comment]
I think you may be misunderstanding the difference between caching and compiling - I can't tell since you didn't include a use case.

To clear things up:

* The `uncache` ViewHelper creates `USER_INT` objects which is why it requires TSFE and is frontend only.
* There is no equivalent for "uncached" rendering in the backend, because:
* The output of ViewHelpers in the backend does not get cached unless you explicitly add a cache around it, in which case *that's* where you must prevent the caching (the ViewHelper would have no effect on that).
* If you meant *compiling* then yes: ViewHelpers do get compiled also in the backend. However, the `uncache` ViewHelper has no effect whatsoever on this behavior.
* What does have an effect on compiling is if you use `<f:cache.disable />` but beware this decreases performance significantly.

So while the request above will not be fulfilled, you probably meant to implement on of the latter two compiling prevention measures. Closing the issue.

**Comment by webloft** [comment]
Thank you for your explanation - but if the viewhelper gets compiled it should at least display true or false. In my case I have tried the following:

```
<v:extension.loaded extensionName="xyz">
            <f:then>Loaded</f:then>
            <f:else>Extension not loaded</f:else>
</v:extension.loaded>
```
Works every time the cache is cleared, next calls displays **nothing**.
Using `<f:cache.disable />` indeed resolves that problem - but then there **is** a cache which prevents the viewhelper getting compiled - just saying.
