### ISSUE TITLE
IfViewHelper: Class 'TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\BooleanNode' not found 

### ISSUE THREAD

**Issue by typecat** [FluidTYPO3/vhs#1452]
Example:
Render then child only if ether of related links and related files of news are given.
`<v:if stack="{
                              0: '{newsItem.relatedLinks -> f:count()}', 1: '>', 2: 0,
                              3: 'OR',
                              4:  '{newsItem.relatedFiles -> f:count()}', 5: '>', 6: 0
}">`
Exception:
> Class 'TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\BooleanNode' not found

EXT:vhs 4.3.3
TYPO3 8.7.10 using EXT:fluid_styled_content

No problems with that structure with same EXT:vhs version and TYPO3 7.6 (any subversion) using EXT:fluid_styled_content

A fix or any workaround is mostly appreciated :)

**Comment by jdreesen** [comment]
See: #1332 & #1275

**Comment by tantegerda1** [comment]
Hm, by looking at it, the code example does not do what you're expecing:
> Render then child only if **both** related links **and** related files of news are given.

but you are using a boolean **OR** operation. If you really like to check if **both** conditions match, then an easy workaround is to nest standard fluid conditions:
```
<f:if condition="{newsItem.relatedLinks -> f:count()} > 0">
    <f:if condition="{newsItem.relatedFiles -> f:count()} >0">
        …
    </f:if>
</f:if>
```
Nitpicks:
- I believe you do not need the comparison `> 0` and not even the `->f:count()`, it should suffice to test for `{newsItem.relatedLinks}` and `{newsItem.relatedFiles}`.
- since TYPO3 8 LTS uses the new standalone Fluid (more recent version with many improvements; as external composer package), you can now write complex conditions using standard fluid `if` ViewHelper
```
<f:if condition="{newsItem.relatedLinks} && {newsItem.relatedFiles}">
    …
</f:if>
```
See the [TYPO3 v8 what's new slides](https://typo3.org/download/release-notes/whats-new).

----
Disclaimer: Did not test what I wrote here, this is just out of my memory. Please test that the condition does actually work as intended, especially at the edge cases.

**Comment by typecat** [comment]
@tantegerda1 Sorry, I actually meant "ether of". So the "OR" condition is correct here. I'll correct it in the description.

**Comment by typecat** [comment]
Thanks @jdreesen I will take a look at it.

**Comment by typecat** [comment]
Totally forgot that conditions like
`<f:if condition="{newsItem.relatedLinks -> f:count()} || {newsItem.relatedFiles -> f:count()}">`
are now possible with TYPO3 8.7. Thanks for the hint @jdreesen !
