### ISSUE TITLE
Condition\Variable\IssetViewHelper fails on TYPO3 7 while TER package still claims it is compatible

### ISSUE THREAD

**Issue by taalas** [FluidTYPO3/vhs#1453]
Hi,

we recently updated VHS to 4.3.3 on some of our TYPO3 7 sites and the IssetViewHelper seems to be broken for us now.

Source code for this VH claims that it will only work in TYPO3 8, while ext_emconf.php still claims compatibility with TYPO3 7:

`'typo3' => '7.6.13-8.7.99',`

Is this an oversight or might more VHs break for TYPO3 installations in the future?

**Comment by NamelessCoder** [comment]
Hi @taalas,

The bad news first: we plan to drop TYPO3 7.6 support in the near future, so it is likely this won't be fixed and you should focus on workarounds (such as comparison with empty string in f:if, or using v:or, or others). There is an incompatibility in the base classes used by TYPO3 v8 and v7 concerning condition ViewHelpers which means that some of the VHS condition ViewHelpers cannot work on both versions at the same time - and so v8 support was chosen for those as it is the future minimum requirement.

In short, the 7.6 support is only partial because it has a couple of exceptions. What I can promise you is that we don't expect any similar breakage happening any time in the future - but 7.6 will not be supported much longer. Part of the reason is the increasing inability to create a version that would work on TYPO3v7 as well as v9 and the pressure to release a new version compatible with v9. You can probably expect one more update for VHS before v7 LTS support gets removed.

So you should definitely look for alternatives to this and possibly other of the VHS condition ViewHelpers (a quick search for `v:condition.` should reveal all). The rule of thumb is: any condition ViewHelper where the variable you pass isn't the only thing used to determine TRUE or FALSE may be affected - i.e., `v:condition.type.isString` isn't affected but `v:condition.variable.isset` is affected because it has to try and read the variable from RenderingContext from a function where only the VH arguments are available.

Sorry this is causing you problems but the good news is, you won't have to do similar fixes often and once v8 LTS becomes your starting base you likely won't run into this type of problem again, as the API that must be supported will be identical on all supported versions of TYPO3.

**Comment by taalas** [comment]
Hi @NamelessCoder ,
thanks for taking the time to answer this in such detail, very much appreciated!

I understand that these changes are necessary to prepare for future TYPO3 releases. The only confusion for us resulted from the package still being flagged as v7-compatible (which I know know means partial compatibility). We will implement workarounds for the VHs in question as you suggested.

Might I suggest (if not already happened) tagging the last release and/or commit that was fully compatible with v7 (just for reference)?

Thanks!
