### ISSUE TITLE
where are the docs with the tag usage examples?

### ISSUE THREAD

**Issue by DanielRuf** [FluidTYPO3/vhs#1464]
I did not find the examples from the documentation.

https://github.com/FluidTYPO3/vhs/tree/development/Documentation

https://fluidtypo3.org/viewhelpers/vhs/master/Random/StringViewHelper.html for exaple has two errors.

It should be
```
<v:random.string length="123" minimumLength="123" maximumLength="123" characters="0123456789abcdef">
	<!-- tag content - may be ignored! -->
</v:random.string>
```

```
{v:random.string(length: 123, minimumLength: 123, maximumLength: 123, characters: '0123456789abcdef')}
```

**Comment by NamelessCoder** [comment]
They are auto-generated - which is why they sometimes don't make a lot of sense. The HTML in question is generated by EXT:schemaker and the same routine is used for all ViewHelpers.

Ideally, each one would have usage examples as PHPDOC class comments (which get parsed as Markdown, see examples throughout VHS) - and it most likely would be a good idea to suppress the output of that semi-broken auto piece when proper docs exist, through some detection in EXT:schemaker.

**Comment by DanielRuf** [comment]
Hm, did not find this exact wrong code in the repo or did I oversee something?

**Comment by ayacoo** [comment]
https://github.com/FluidTYPO3/vhs/commit/2bfd7c6d5450b1bc45c6a98107ae690da778d4ca#diff-d477145e2d727ff5af4f5a633a394c50

But the page is outdated as described: https://fluidtypo3.org/viewhelpers/vhs/master/Random/StringViewHelper.html

**Comment by neufeind** [comment]
@NamelessCoder Can you trigger a recreation of that documentation-page maybe?

**Comment by NamelessCoder** [comment]
@neufeind I'm phasing the VH docs out in favor of https://viewhelpers.fluidtypo3.org which doesn't contain those examples - if/when they get added in the future I will create an improved version that renders long tags better and is more sensitive to whether ViewHelpers also make sense to use inline with `->` passing.
