### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by netengine-at** [FluidTYPO3/vhs#1478]
PHP Parse error:  syntax error, unexpected '?' in 
typo3conf/ext/vhs/Classes/ViewHelpers/Format/PregReplaceViewHelper.php on line 49

Line: 45
`$subject = $arguments['subject'] ?? $renderChildrenClosure();`

should be:
`$subject = $arguments['subject'] ?: $renderChildrenClosure();`

**Comment by tantegerda1** [comment]
Hi @netengine-at,

please help us help you by providing:
- the vhs version in use
- the php version in use

Cheers,
Ludwig

**Comment by netengine-at** [comment]
Sorry 😊

VHS: Fluid ViewHelpers  - 4.4.0
PHP: 5.5 und PHP 7.0

**Comment by tantegerda1** [comment]
np.
The `??` is the [Null Coalescing Operator](https://secure.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce). It is available since PHP 7, which is [explicitely](https://github.com/FluidTYPO3/vhs/blob/4.4.0/composer.json#L34) [required](https://github.com/FluidTYPO3/vhs/blob/4.4.0/ext_emconf.php#L26) by VHS 4.4.

Does the parse error occur even when using PHP 7?

**Comment by netengine-at** [comment]
my bad, I changed the PHP Version in .htaccess but didn't check that it really had changed (so in reality it was PHP 5.6). 

Sorry, for the wasted time!
