### ISSUE TITLE
v:iterator.slice cannot cast QueryResult to string

### ISSUE THREAD

**Issue by iamandrewluca** [FluidTYPO3/vhs#1481]
```
typo3: 7.6.27
flux: 8.2.1
vhs: 4.4.0
```

Today wanted to migrate from `3.1.0` to `4.4.0`  
Fixed some changes. But I encountered some pages with error
```
Cannot cast object of type "TYPO3\CMS\Extbase\Persistence\Generic\QueryResult" to string.
```
Then I found out that this is caused when I use `v:iterator.slice` with `as` argument, and it seems that `v:iterator.chunk` also has some problems related to `as` argument and `ObjectStorage`

Example does not work
```html
<v:iterator.slice haystack="{news}" length="2" as="auxVar" />
<f:debug>{auxVar}</f:debug>
```

Example works
```html
<v:variable.set name="auxVar" value="{v:iterator.slice(haystack: news, length: 2)}" />
<f:debug>{auxVar}</f:debug>
```

Then I got home, and tried to simulate this again using `vhs` branch `develoment`, and using `TYPO3` `v8.7.13`, on a clean environemnt, same problem was encountered.  

I tried to debug through `vhs` extension and couldn't find the root of problem, maybe this even is not a `vhs` problem. Can someone help please? Thanks!

<details>
<summary>Error image in v8 without stack trace</summary>

![image](https://user-images.githubusercontent.com/1881266/39548553-a4a11964-4e63-11e8-813a-98f9a3a77ee2.png)
</details>

<details>
<summary>Error image in v7 with stack trace</summary>

![image](https://user-images.githubusercontent.com/1881266/39563434-d90c306c-4eb8-11e8-9a1d-b68f79c849ea.png)

</details>

**Comment by NamelessCoder** [comment]
When you use the `as` argument, the variable you declare becomes available _inside the tag contents only_. The exception to this is when you use `f:variable` or `v:variable.set` which explicitly "leaks" the variable to make it exist also after the VH has finished.

The error seems to be somewhat unrelated, too. It is likely caused by variables not having the values you expect, because of the assignment problem.

**Comment by tantegerda1** [comment]
To illustrate the above, you would write the first example as
```html
<v:iterator.slice haystack="{news}" length="2" as="auxVar">
    <!-- inside; variable {auxVar} is set -->
    <f:debug>{auxVar}</f:debug>
</v:iterator.slice>
<!-- outside; variable {auxVar} is not set -->
```

**Comment by iamandrewluca** [comment]
Ok, moved inside, still error.

```html
<v:iterator.slice haystack="{news}" length="2" as="auxVar">
    <f:debug>{auxVar}</f:debug>
</v:iterator.slice>
```

![image](https://user-images.githubusercontent.com/1881266/39566014-c93ac43c-4ec2-11e8-939f-38fd39fe95dc.png)

**Comment by NamelessCoder** [comment]
Here's the method responsible for converting your QueryResult in `v:iterator.*` and others, it's definitely got support for QueryResult (and will call ->toArray() on the result).

https://github.com/FluidTYPO3/vhs/blob/development/Classes/Traits/ArrayConsumingViewHelperTrait.php#L90

If you debug, this is where I would start - but I still am convinced the error isn't happening inside `v:iterator.slice` but is rather caused by other factors like the ones with whitespace or unexpected variable types.

**Comment by iamandrewluca** [comment]
Yes, yesterday when I debuged, found this place where `QueryResult` is converted.  
Thanks for support. I'll investigate more.

**Comment by igodorogea** [comment]
I think the "problem" is here https://github.com/TYPO3/Fluid/blob/master/src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php#L99
since in case of `<v:iterator.slice />` and `<v:iterator.chunk />` (at least, that's the VH's I checked) the if condition will be always true and in that case `$renderChildrenClosure` will always return `$arguments['haystack']` for slice, and `$arguments['subject']` for chunk.

So, I guess, since version 4 it's no longer possible to use the syntax:
```xml
<v:iterator.{slice,chunk} {haystack,subject}="records" as="recordsBlock">
    <f:for each="{recordsBlock}" as="record"></f:for>
    ... or something else
</v:iterator.{slice,chunk}>
```
