### ISSUE TITLE
Migrating from TYPO3_DB

### ISSUE THREAD

**Issue by rafu1987** [FluidTYPO3/vhs#1491]
There are still some occurrences of old TYPO3_DB, but the extension is marked to work with TYPO3 9.3.x. Either remove the TYPO3_DB calls or add the `typo3db_legacy` extension as a dependency.

https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Database/Migration/Index.html
https://extensions.typo3.org/extension/typo3db_legacy/

**Comment by cedricziel** [comment]
Aye, would you mind creating a pull request for that?

**Comment by NamelessCoder** [comment]
> Aye, would you mind creating a pull request for that?

And by "that" we'd absolutely prefer a refactoring of the limited number of places where we currently don't use Doctrine ;)

**Comment by rafu1987** [comment]
I will look into it. I think, first it should be made compatible with TYPO3 9.3.x, as currently it isn't and then think about refactoring (however this would be implemented).

**Comment by NamelessCoder** [comment]
The way you're solving this is actually precisely what I meant with "refactoring" so: excellent work, it is greatly appreciated if you continue in this direction!

**Comment by rafu1987** [comment]
@NamelessCoder thanks you very much :-)
I created a pull request and removed the class check. Also, I removed the class check here in this file, too: `Classes/ViewHelpers/Content/AbstractContentViewHelper.php`

I added the doctrine stuff here and fixed #1433 along with it: `Classes/ViewHelpers/Resource/AbstractResourceViewHelper.php`

And added the doctrine stuff in this file as well: `Classes/ViewHelpers/Resource/Record/FalViewHelper.php`

Now, all the TYPO3_DB calls should be replaced and I hope everything still works as expected :-)

**Comment by NamelessCoder** [comment]
@glucka For https://github.com/FluidTYPO3/vhs/pull/1492 the main missing thing is to use named parameters in the doctrine queries as opposed to the raw value comparisons. Aside from that there could be other occurrences that also need to be taken care of.

You can definitely help to complete it. But in order to do that there's a little something that has to be officially taken care of ;)

*I've added you to the team of FluidTYPO3 maintainers!*

Welcome on board and thank you so much for all the help. If/when you accept the invitation you will gain access to pushing updates to the PR branch on the users' forks and that's a good way to help push stalled PRs along.

I have only a few "rules" you should keep in mind:

* Please don't push to development, staging or master branches directly for the time being.
* Please don't merge pull requests that have not been approved by another maintainer and if you have any doubt, please request reviews from me.
* Please don't create branches on the upstream repositories when you are creating your own pull requests; keep creating them in your fork - as maintainers we'll all have push access anyway.
* Obviously, don't change repository settings like hooks or services :)

And if you have any questions at all just ask!

**Comment by cedricziel** [comment]
Awesome, welcome, @glucka !

**Comment by glucka** [comment]
Thanks for your trust! I have to learn a lot ;)

**Comment by cedricziel** [comment]
Perfect opportunity - let us know if you have any questions

**Comment by glucka** [comment]
Solved with #1519
