### ISSUE TITLE
assets viewhelper name collosion betwenn styles and scripts

### ISSUE THREAD

**Issue by jonakieling** [FluidTYPO3/vhs#1506]
Hi Everyone,

I recently stumbled upon a name collision issue when using the same name for a style asset and a script asset. Since it happened while migrating asset registration (previously with the TYPO3 typoscript page properties, which don't allow name collisions across asset types)

I'm currently using vhs 4.3.3 with TYPO3 7.6.29 but noticed the same code in the current master.

If separating styles and scripts is something that would make sense I'd gladly provide a PR introducing a new field for the AbstractAssetViewHelper defining a prefix that can be overridden by its subclasses.
Replacing
`$GLOBALS['VhsAssets'][$name]`
with
`$GLOBALS['VhsAssets'][$this->prefix][$name]`
or for backwards compatibility something like
`$GLOBALS['VhsAssets'][$this->prefix . ':' . $name]`

all the best
jona

**Comment by NamelessCoder** [comment]
Hi Jona,

Thanks for reporting this, and for offering to make a PR - but we will have to leave this as "won't fix" since VHS integrates with Fluid and TS without difference between CSS/JS (or indeed any other type of asset) and adding such distinction in either storage or API triggers a significant amount of required refactoring that would constitute multiple breaking changes. Since TYPO3v10 LTS has a native method for asset inclusion and VHS's asset solution will be deprecated at some point, doing the breaking change refactoring would probably cause more harm than good.

Even so, it is great to have this documented in an issue so anyone searching for this problem will know how to avoid problems with colliding asset names!
