### ISSUE TITLE
Once.Cookie ViewHelper doesn't work

### ISSUE THREAD

**Issue by dotdash** [FluidTYPO3/vhs#1544]
The `Once.Cookie` ViewHelper doesn't work at all. The first the the page is rendered, the content is missing, and then it is shown all the time. Almost backwards, but that the content is missing initially is not user-dependent.

Looking at the code, I see no way that `storeIdentifier()` would be called, which fits the fact that I never get any cookie. But there are other quirks as well, for example `removeIfExpired` removes the cookie unconditionally, and `removeCookie` doesn't just unset the cookie, but also tries to unset a field in the `$_SESSION` array using the same identifier, which seems bad.

**Comment by NamelessCoder** [comment]
Hi @dotdash - you're right, I think at some point the `storeIdentifier()` call was removed because of course that should be called. I believe it was once there in the "then" rendering functions. And about `v:once.cookie` removing the session variable I'm pretty sure this was because the cookie variable remained active in session - but I don't exactly remember clearly, it's been a handful of years since this was written.

Errors seem to have been introduced with https://github.com/FluidTYPO3/vhs/commit/e0812ea2c6988a09f45b28e78e5bfd502bdc7552#diff-611745fd0d4e231b9a3f0ed64d482fcb which I can only blame myself for.

**Comment by Jan1989** [comment]
HI @NamelessCoder,

I use the latest vhs version and experienced the problem described above as well.
I removed the 'removeIfExpired' function in the cookie viewhelper in order to test if there is still a problem with expired cookies.
After removing the 'removeIfExpired' function the cookie viewhelper worked as expected.

Additionally i adjusted the evaluateCondition function of the Abstract class.
I added the missing store function after evaluating if the then or the else child should be rendered. (See snippet bellow)

`/**
     * @param array|null $arguments
     * @return boolean
     */
    protected static function evaluateCondition($arguments = null)
    {
        static::removeIfExpired($arguments);
        $shouldSkip = static::assertShouldSkip($arguments) === false;
        static::storeIdentifier($arguments);
        return $shouldSkip;
    }`

(I tested this fix for the session and cookie viewhelper.)

Would this be a valid fix and could I create a pull request to remove/change the functions or do you still see any problems here and would like a different approach?

Greetings, Jan

**Comment by NamelessCoder** [comment]
Hi @Jan1989,

It might be best to call `storeIdentifier` from within `removeIfExpired` of the cookie ViewHelper (and others that need to re-set an identifier). Feel free to create your pull request with the code you have now - it helps to have some code to relate to.

The thing I'm not sure about is whether it's a good idea to have all "once" ViewHelper always re-set the identifier every time the condition is evaluated (as some do cause persistence).

**Comment by Jan1989** [comment]
I think if we call `storeIdentifier` from within `removeIfExpired` we could get a problem with `assertShouldSkip` cause we need to evaluate after `removeIfExpired` and before `storeIdentifier`.

**Comment by NamelessCoder** [comment]
Solved by 71728a6b5e9dc6b51089aa2f40e3014cf113a289
