### ISSUE TITLE
[BC break] v:variable.typoscript loads from wrong pagetree within <f:section name="Configuration">

### ISSUE THREAD

**Issue by spackmat** [FluidTYPO3/vhs#1584]
Hi,

I don't know if this is a new issue (currently I run TYPO3 8.7.24 with vhs 5.2.0 and flux 9.2.0) and I'm not sure if this was the case when I wrote the extension earlier.

I have a template which loads the items for a `flux:field.select` from TypoScript like this:

    <f:section name="Configuration">
        <f:debug>{v:variable.typoscript(path: 'plugin.tx_my_providerextension.config.filterCategories')}</f:debug>
        <flux:form id="myFormId" options="{group: 'FCE'}">
            <flux:field.select
                name="settings.test123"
                label="Test123"
                items="{v:variable.typoscript(path: 'plugin.tx_my_providerextension.config.filterCategories')}"
                default=""
                multiple="true"
                renderType="selectCheckBox"
            />
        </flux:form>
    </f:section>

Rading the categories in the `main` and `preview` sections with `{v:variable.typoscript(path: 'plugin.tx_my_providerextension.config.filterCategories')}` works as expected and the items defined in the setup for that pagetree are loaded (as they are also shown in the object browser of that page).

But the form shows me the items configured in the setup of the first pagetree. This is weird because this are not the default values defined in the setup.txt of my extension, but really the ones of the first pagetree: When I make another pagetree the first, its values are loaded for all other pagetrees, but still only in the form, not in `main`.

Anyone with ideas on that? How can I load values from the setup of the current pagetree? Is this a bug or am I doing anything wrong here?

Edit: It is even simpler, the `<f:debug>{v:variable.typoscript(path: 'plugin.tx_my_providerextension.config.filterCategories')}</f:debug>` also prints the wrong values within `<f:section name="Configuration">` and the right ones within `<f:section name="Preview">` (and Main)

Update: The debug prints the right values, when I open the page containing such an content element inside the page module. So in general the `<f:section name="Configuration">` gets the right context. But when I edit one of these content elements, the debug prints the wrong values (from the first pagetree) and uses those also for the items of the select input. Really weird.

**Comment by spackmat** [comment]
I tested this with another site running TYPO3 9.5.5 and could reproduce the behavior. Just take these steps to reproduce this:

1. Insert a `<f:debug>{v:variable.typoscript(path: 'plugin.tx_my_providerextension.config.filterCategories')}</f:debug>` inside a Configuration section of any content template.
2. Set values for that object path inside the TypoScript-Setup for the first pagetree of an installation.
3. Set other values for that object path inside the TypoScript-Setup for another pagetree of this installation.
4. Visit a page of that other pagetree containing the modified content element inside the page module and observe the correct values configured in the current pagetree in debug output.
5. Open the edit view of the content element and observe the values configured in the setup of the first pagetree in the debug output instead of the values configured in the current pagetree.
6. If you like, make another pagetree the first and observe that within the edit view, always the values configured for the first pagetree of the installation is used.

**Comment by spackmat** [comment]
I could talk to an editor of that particular website and he said this definitively worked in the past and indeed are there some values only existing in the second pagetree stored within the flexforms-xml, so in the past, they must have been a choice of the select field. So this looks like a clear BC-break from my point of view.

**Comment by NamelessCoder** [comment]
The reason is the following:

1. VHS `v:variable.typoscript` uses ConfigurationManager by loading the class from interface name.
2. This will then load whichever ConfigurationManagerInterface implementation is used on the system (hint!)
3. Flux used to provide a ConfigurationManagerInterface implementation to solve a couple of missing corners in the TYPO3 core's ConfigurationManager in particular concerning resolving the right page UID in certain contexts (BE, CLI) due to not having a proper page ID awareness.
4. Flux removed this ConfigurationManagerInterface implementation for a couple of reasons. One being that any such implementation will conflict with others. Another being that any overrides have to be maintained and kept in sync with the core itself - otherwise, if/when this problem would be fixed in the core, Flux's implementation would be *worse* than the core's.
5. This removal was a breaking change, therefore the version of Flux that removed it, was major 9.0. See https://github.com/FluidTYPO3/flux/commit/4e147ef5b1ec6e14730cea75067a09461a110102.
6. The reason it works in `Preview` but not in `Configuration` is two-fold: the `Configuration` section is extracted at a different point in the runtime which has no predictable page UID (in GET, POST, record, repository or other) - therefore, whether or not it works in `Configuration` _depends on which context you're in_. And `Preview` coincidentally is rendered in a context that does use a predictable GET parameter which is recognised by the core's ConfigurationManager, allowing it to read the right TS root line.

These things combined explains why this used to work (though it isn't related to VHS) and why it no longer does. I am sorry to say that this particular combination will not be recreated: neither Flux nor VHS will provide ConfigurationManagerInterface implementations in the future for the reasons stated above.

Generally speaking you should make every effort to *avoid using any page context specific things like typoscript within Fluid templates that operate in backend, which includes Flux templates' Configuration and Preview sections*.

Your possible solutions:

1. Create a ConfigurationManagerInterface implementation like the one removed from Flux.
2. Use a different means of defining the inherited variables, which works in BE (pageTSconfig, record fields, "site" configuration option, etc.) that you then process accordingly.
3. Implement a custom `Provider` class that works with your content types and adds the required variables by looking them up in TypoScript with a page UID that you decide/resolve as your use case requires.

I realise this probably isn't the answer you looked for but it's the best we can do. The overrides will not be reintroduced and this strategy will be actively avoided in the future, in favor of whichever behavior the TYPO3 core provides - good and bad.

**Comment by spackmat** [comment]
Thank you for that elaborate answer! You are right, that was not what I was looking for, but I understand the reasons for that. So, at least, please document that behavior, since I spent about one full workday (not accountable in that case) to figure out what the problem was.

As I am not that deep inside coding here and just integrate projects into TYPO3, only those in point 2 are feasible for me. My favorite would be to implement that into page configuration, but there I have [that problem](https://github.com/FluidTYPO3/flux/issues/1696) circumventing that way. The next one would be to set the options in pageTS, but I don't know how to access that inside my content element in backend, preview and frontend-rendering, where the configurated values are also used.

**Comment by NamelessCoder** [comment]
Item 3 gives you the greatest amount of freedom to decide exactly where to store the variables. That also has to be done if using the pageTSconfig solution since this doesn't get assigned in templates automatically.

Don't be afraid of the `Provider` class pattern, it's not too complicated. That as API lets you do so much more than the other ways. Create a class, make sure it responds to the right `CType` value, override the `getTemplateVariables` method and add variables from any source you like.

You can also create a ViewHelper if that's easier. You are allowed to use a custom ViewHelper around the `flux:form` tag to insert other variables that the `flux:form` uses as labels, displayCond, whatever. But you'd have to use that ViewHelper everywhere with one occurrence in `Configuration`, another in `Preview`, another in `Main` (if you need the variables there) and so on.

**Comment by spackmat** [comment]
Thank you, I'll have a look hat that.
