### ISSUE TITLE
Vhs 6.0.3 Call to a member function getRequest() on null

### ISSUE THREAD

**Issue by prdt3e** [FluidTYPO3/vhs#1673]
Click to Site-Configuration -> add news Site-Configuration.

Call to a member function getRequest() on null
typo3conf/ext/vhs/Classes/ViewHelpers/Extension/AbstractExtensionViewHelper.php line 55

VHS: 6.0.3
Typo3: 10.4.5

**Comment by NamelessCoder** [comment]
It appears that you have some template which is being rendered inside the site configuration view (could be a Flux content element or page template) in which you use a ViewHelper from within the `v:extension.*` scope and which you do not provide the `extensionName` when calling.

The ViewHelpers within that scope either require that you specify the extension name as argument, or use the ViewHelper as part of a *frontend request executed by a controller*  because the extension name is only possible to extract from the controller context - and it doesn't exist unless the mentioned condition is met.

To solve this, identity the exact ViewHelper usage that causes the problem and make sure you specify the `extensionName` parameter.
