### ISSUE TITLE
v:page.rootline : Exception when page doesn't exist

### ISSUE THREAD

**Issue by sdelcroix** [FluidTYPO3/vhs#1688]
Hi,

we have custom fluid styled contents which contain link field (t3://) which allows editors to select a page, and In backend preview templates, we use v:page.rootline to render a rootline to this page.

Sometimes editors delete the page but don't update the content element.

Since vhs 6.0.4 (that uses RootlineUtility class), TYPO3 raises an exception if the page is deleted.

`(1/1) #1343589451 TYPO3\CMS\Core\Exception\Page\PageNotFoundException`
`Could not fetch page data for uid 3070.`

**Comment by bj0hn** [comment]
I can confirm, have the same problem.

**Comment by NamelessCoder** [comment]
This should perhaps be reported to https://forge.typo3.org - if this is still failing, the likely cause is that the TYPO3 Context (the class, not the Application Context) is being misconfigured or is intentionally configured to still enforce the `deleted = 0` clause on queries that select the root line; when you are in a BE-user situation. My two cents is that it is probably intentional even in BE - previewing/rootlining a _hidden_ page is a perfectly valid use case, but a _deleted_ page certainly should not be possible and should yield an error anywhere except perhaps in the Recycler (technically, it no longer exists).

VHS will not attempt to fix this issue by creating a custom Context that shows you deleted pages, or by implementing a custom RootLineUtility capable of skipping/ignoring deleted pages based on context. I'd suggest using the workaround by @bj0hn since your use case is a bit special.
