### ISSUE TITLE
Sad about new Documentation 

### ISSUE THREAD

**Issue by fischhase** [FluidTYPO3/vhs#1693]
Hallo dear Developers,
thank you for your great work. Your Extension is one of my favourites. But one thing I am really sad about: Your Documentation has changed. Now it is just a automatical generated List of commands and parameters. Once there was a documentation, much better in design and function. It had working examples, inline formats and maybe also comments (I don't remeber exactly). 

https://viewhelpers.fluidtypo3.org/fluidtypo3/vhs/5.0.1/

Maybe it was too much work to keep it up to date, but know it really doesn't help so much.

Thanks anyway
Martin

**Comment by MarkusBausK** [comment]
I can confirm this... The old docs were a really important daily tool for us :-(

**Comment by sebastianhomeier** [comment]
I second that. Also, documentation for 6.x versions is missing completely.

**Comment by grimmcreative** [comment]
Would be so great if we can get back the old Version.
I would sign up voluntarily also to keep it up2date.

**Comment by me84** [comment]
Thats true. I'm absolutely missing the old Docs.
Why cant we get both?

**Comment by ingeniumdesign** [comment]
yes we need the Code Examples back 👍

**Comment by NamelessCoder** [comment]
In the future, ViewHelper references are updated automatically and can be found on https://docs.typo3.org/p/fluidtypo3/vhs/6.1/en-us/ (select your version in the left menu). A fully automated solution has been implemented - after acknowledging that even the reduced manual workload required by the more recent iteration of the documentation still caused the documentation to quickly become outdated.

So: every ViewHelper in VHS has had its usage examples updated to render correctly in this new location. From now on, this is updated automatically with every single release that happens.

-----

For the ones that are sad about the code examples: I'm sorry that you miss this, but it is unlikely to come back. The old documentation renderer created these code examples by very loosely guessing what a proper value for a given argument would be and then rendering the example with such assumed/guessed arguments. This was *very* far from perfect and in too many cases caused the documentation to contain examples that would never work if you copy-pasted them.

In addition, the ViewHelper documentation is now rendered by the official ViewHelper documentation generator and as such, follows the same standards and produces the same output as official TYPO3 core ViewHelper documentation. It is therefore not possible to restore this guessed approximation without also activating it for TYPO3 core ViewHelpers and due to the misleading nature of guessed argument values, this would never be accepted there.

The *right* way to get these examples would be to update the ViewHelper documentation within the PHPdoc class comment of each ViewHelper class (and you are absolutely more than welcome to help with this!) - but the automated, guessed approximation is unlikely to ever return.

So I'm sorry if you still miss these examples. I hope the new documentation rendering is at least more useful to you. And I hope that those of you who really liked the code examples will help build _proper_ code examples by contributing changes to VHS to add these examples for the ViewHelpers that currently don't have them!

**Comment by seirerman** [comment]
Could you redirect the documentation link on https://extensions.typo3.org/extension/vhs to the new page, please? This link is usually the first place I look when I want to RTFM.
