### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/vhs#1746]
Are there any plan for supporting PHP 8.0 any time soon? Would be helpful for using TYPO3 11 LTS (see #1742).

**Comment by NamelessCoder** [comment]
Current development branch is compatible with PHP 8.1, but may not be E_NOTICE safe. Given that the TYPO3 core itself isn't E_NOTICE safe either, I don't take that as a huge issue. General advise for anyone reading this: configure your TYPO3 to not produce exceptions on E_NOTICE level warnings - otherwise you would very quickly run into issues not just with VHS.
