### ISSUE TITLE
v:render.uncache problem in v6.1.1 (TYPO3 v11)

### ISSUE THREAD

**Issue by gckng** [FluidTYPO3/vhs#1765]
Hey there,
first of all thank you very much for launching vhs 6.1 supporting TYPO v11.
I just installed this version and tried to use the v:render.uncache viewhelper but got this issue:
PHP Warning: Undefined array key "controllerExtensionName" in .../typo3conf/ext/vhs/Classes/View/UncacheTemplateView.php line 87

I just used the viewhelper as known in former versions:
<v:render.uncache partial="Header" arguments="{_all}"></v:render.uncache>

I already tried to set a fix typoscript value in my FLUIDTEMPLATE settings, but that doesn't help.
extbase.controllerExtensionName = MyExtension

Is there anything I'm missing? Thanks in advance for your help!

**Comment by NamelessCoder** [comment]
Hi @gckng - thanks for the report!

There was a mistake in UncacheTemplateView, the line `$request->setControllerExtensionName($conf['controllerContext']['controllerExtensionName']);` should actually be `$request->setControllerExtensionName($conf['controllerContext']['extensionName']);`. I didn't notice this because I have `E_NOTICE` disabled and my test setup didn't use that property of the controller context. So thanks for spotting it and reporting :)

I'll make a fix and schedule a bugfix release soon.

**Comment by gckng** [comment]
Cheers, thanks for the quick response and the bugfix release. Awesome support!
