### ISSUE TITLE
v:content.render influences action uri generation

### ISSUE THREAD

**Issue by TrueType** [FluidTYPO3/vhs#1885]
**I have checked that the bug exists in the `dev-development` branch**
YES

I am not sure, if it is a bug. Just want to report my experience, which broke my code:

TYPO3v10  
VHS v6.1.3 -> v7 / dev-development

This was working with v6.1.3

    <v:content.render contentUids="{0:123}"></v:content.render>
    <f:form id="xy" pageUid="234" name="user" action="new">

With v7 I had to add an extensionName parameter

    <v:content.render contentUids="{0:123}"></v:content.render>
    <f:form id="xy" pageUid="234" name="user" action="new" extensionName="asdf">

It seems the context of the action uri generation changes with v:content.render

**Comment by NamelessCoder** [comment]
I think this has to do with what is being rendered by v:content.render, rather than v:content.render itself. If I'm right, one of the content elements rendered by the VH is changing one or more properties of either the request's ExtbaseParameters attribute, the ControllerContext (if there is legacy stuff involved) or one of the (Singleton) classes holding UriBuilder.

Whichever the case might be, unless that "inner" problem is caused by another VHS or Flux implementation, there wouldn't be anything I could do about it. Assuming I'm right, it would be an unfortunate side effect of TYPO3 treating multiple context-specific classes as singletons/shared instances which "bleed" context info.

It is *always* safer and better to provide the extension key, plugin name, and controller name when building URLs. Depending on the automatic resolving of these things from context is too easily broken (and won't work anywhere else except in that specific controller/action/plugin/extension).

**Comment by TrueType** [comment]
@NamelessCoder Thx very much for your reply. I have a ticket for this and will come back here, if I have something to share. Please close.
