### ISSUE TITLE
f:format.replace does not work if used in inline syntax

### ISSUE THREAD

**Issue by christophrunkel** [FluidTYPO3/vhs#1895]
The following syntax used to work in Typo3 11.5 / VHS 6.0.3

`<div id="c{data.uid}" class="frame {data.tx_bsdist_customcss} frame-{v:format.replace(substring: '__', content: '{data.frame_class}', replacement: ' ')}>`

In Typo3 12.4 this fails, i have set a variable first, then use it inline. Not critical for me, but an awful lot of templates have to be checked and i am not sure, this works in all the cases:

This is the workaround:

```
<f:variable name="frameclasses"><v:format.replace substring="__" replacement=" ">{data.frame_class}</v:format.replace></f:variable>
<div id="c{data.uid}" class="frame layoutdefault yyy frame-**{frameclasses}**>
```
      
Would be nice if the inline syntax would work again.

**Comment by NamelessCoder** [comment]
If that exact same syntax with the exact same variables worked before, but doesn't work now - then that clearly indicates it's a bug in Fluid, likely caused by some adjustment to the regular expression that matches variable references in inline syntax within tag attributes.

In any case, VHS isn't responsible for the _parsing_ behavior and I just now verified that the ViewHelper in question does work in line mode, and works with either `content` argument or tag content / inline pass syntax.

It's possible that using this syntax would also work as a (simpler) workaround:

```xml
{data.frame_class -> v:format.replace(substring: '__', replacement: ' ')}
```

Or even just removing the redundant quotes may work:

```xml
{v:format.replace(substring: '__', content: data.frame_class, replacement: ' ')}
```
