### ISSUE TITLE
Feature request: Generic record loading view helper

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#1913]
**Describe the solution you'd like**
VHS should ship with a generic record loading view helper that allows e.g. to fetch a `tt_content` record with a given UID when fluid is used to render backend preview of mask elements.

There should be an attribute to disable access restrictions like "hidden", start- and stop time.

```
<v:record table="tt_content" uid="23"/>
<v:record table="tt_content" uid="23" column="tx_container_parent"/>
<v:record table="tt_content" uid="23" column="tx_container_parent" ignoreAccessRestrictions="1"/>
```

**Describe alternatives you've considered or workarounds you currently have to use**
- `vhs:resource.record` throws an exception when the `tt_content` record is disabled (see #960)
- `vhs:content.get` does not work in the backend
- [loading records with TypoScript](https://www.typo-script.de/blog/typo3/fluid-cobject-records/) does not work since the backend context does not have TypoScript available

**Comment by NamelessCoder** [comment]
I hesitate to add a _generic_ record loading ViewHelper simply because that would allow loading any arbitrary record if anyone has access to any template. That being said, there are a couple of ViewHelpers which can do that but only for specific tables:

* `tt_content` can be fetched with `v:content.get`, either by UID or colPos.
* `pages` can be fetched in a couple of ways, any of the `menu` scope ViewHelpers or `v:page.info`.
* And as you probably already know, `sys_file_reference` relations can be fetched for any table (but only the _relations_, not the record they relate to).

I should note that all of these will use whichever SQL constraints TYPO3 will auto-apply to a connection based on FE/BE context. So if someone needed a different set of constraints applied, they'd need to create a custom ViewHelper to do so (I would strongly urge to do so with one ViewHelper per table so arbitrary tables cannot be specified at template level).

It's very intentional that only these types are supported. I've also wanted to add a `site.configuration` ViewHelper for some time to read out the `Site` instance but I never got around to it. These are the only types I currently consider safe (enough) even if someone gained access to read aribtrary records from the specific tables involved.

About your attempted workarounds:

* Default SQL restrictions are applied by TYPO3 based on context, anything beyond that has to be implemented as a custom solution.
* While `v:content.get` doesn't work in BE context, `v:content.info` does - with some limitations. Mainly that 1) you have to specify the content UID and 2) in the non-default language it will attempt to do language overlay via TSFE. Both of those constraints can be circumvented by simulating TSFE (VHS has no built-in way to do this, though). This might be enough to solve your use case.
* TS is definitely not the right tool for the job in BE context.

In the case of EXT:mask preview rendering I don't know what solution they implemented, but if this is based on the core's native preview rendering either through hook, event or `PreviewRendererInterface` implementation it should be possible for you to override or pre-process that solution to attach additional variables. Hint for v12: `PageContentPreviewRenderingEvent` allows you to `setRecord($record)` and TYPO3's standard content preview renderer will assign each column of that record as template variable if you define Fluid-based rendering with pageTSconfig in `mod.web_layout.$table.preview.$CType`. You could use this to attach virtual columns to the record and access those as variables in the template.

Hope this helps, even though I have to reject to feature request as-such!

**Comment by cweiske** [comment]
Thank you for the detailled explanation!
