### ISSUE TITLE
File /pageMedia/ does not exist

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#747]
### I have code:
~~~
<v:resource.image identifier="{v:page.resources.fal(uid: '{uid}') -> v:iterator.extract(key: 'id')}" />
~~~
**or**
~~~
<f:for each="{v:page.resources.fal(uid: '{uid}')}" as="image">
	<f:image src="{image.uid}" treatIdAsReference="1" alt="{image.name}" title="{title}" />
</f:for>
~~~
By attaching a picture the page with ID=2.
On output on all pages, I have a image ... <img src="fileadmin/image.png">
I go to the page with ID=1, all good
... when I go to the page with ID=2, I get error
~~~
Oops, an error occurred!
File / pageMedia/ does not exist.
~~~
### My installing
TYPO3 6.2.9
EXT: view	 2.0.0
EXT: vhs	2.2.0
EXT: flux	7.1.2
EXT: fluidpages 3.1.2
EXT: fluidcontent 4.1.1
EXT: fluidcontent_core 1.0.2

**Comment by grimmcreative** [comment]
Hi, i don´t know exactly what you want to achieve but if you want to have the images places in the site resources by fal try this one out.

<v:page.resources.fal table="pages" field="media" uid="{page.uid}" as="images">
	<f:for each="{images}" as="image">
		<f:image src="{image.url}" alt="{image.alternative}" />
	</f:for>
</v:page.resources.fal>

**Comment by typo3ua** [comment]
I did so and so ...

**Comment by grimmcreative** [comment]
Supposed to mean? Could the code block to help you now?

**Comment by grimmcreative** [comment]
```
<v:page.resources.fal table="pages" field="media" uid="{page.uid}" as="images">
	<f:for each="{images}" as="image">
		<f:image src="{image.url}" alt="{image.alternative}" />
	</f:for>
</v:page.resources.fal>
```

will definitely work (tested)
And there is nothing else todo. there must only be an image in the page resources tab.
If there is no image, nothing will render.

**Comment by typo3ua** [comment]
Yes, there is image in the page resources tab, but when I go to the page on frontend, I get error

**Comment by grimmcreative** [comment]
you should turn on all error reporting to see exactly whats going on.
I can not reproduce it. All works fine. 

Have you checked your image processing settings?
If you made an update to 6.2 have you checked your image migrations 
"Migrate all file relations from tt_content.image and pages.media"
before migration check your [SYS][compat_version]

**Comment by typo3ua** [comment]
I found the cause ...
~~~
{v:resource.record.fal(record: page, field: 'media', table: 'pages') -> v:iterator.extract(key: 'uid') -> v:iterator.first() -> v:variable.set(name: 'pageMedia')}

<f:if condition="{pageMedia}"><v:page.header.meta name="og:image" content="{f:uri.image(src: '{pageMedia}', treatIdAsReference: '1', maxHeight: '1024', maxWidth: '1024') -> v:format.prepend(add: '{v:site.url() -> v:format.substring(length: \'-1\')}')}" /></f:if>
~~~
Now need to determine why?

**Comment by NamelessCoder** [comment]
**Please explain what you are trying to achieve, or people have no clue how to help you!** Use Max's suggestion or debug your complicated inline statement to make sure that the syntax is correct and that each step of the inline expression is returning the correct value.

And please ask this type of usage question on IRC instead of as a bug report - because this problem is not caused by VHS but rather by the way you use the ViewHelpers/variables. A valid alternative has been given - if you do not wish to use it, I suggest you debug your template locally as described above and if you still get no results, ask your question on IRC and make sure you explain exactly what you are trying to achieve.

Right now you are causing emails to be sent to every team member every time you make a new attempt and we, the team, would very much appreciate if you don't do this and use IRC instead.
