### ISSUE TITLE
getContentRecordsFromPage - unusual language handling

### ISSUE THREAD

**Issue by sgalinski** [FluidTYPO3/vhs#761]
The function should always fetch the elements set to the default and all language options (-1, 0) and maybe all elements that are in the requested fallback language (sys_language_content) and which don't have a l10n parent.
Currently the function fetches all elements that are set to the default language and the requested one. This doesn't works perfectly, because getRecordOverlay cannot work in such cases like expected anymore. In example you get trouble with the extension languagevisibility which requires the correct execution of this function.

You can find a good article related to this here: https://www.felixnagel.com/blog/artikel/2010/06/24/mehrsprachige-typo3-extensions-getrecordoverlay-richtig-einsetzen/

My current changes for the function as a workaround:

```
//          $hideUntranslated = (boolean) $this->arguments['hideUntranslated'];
//          $currentLanguage = $GLOBALS['TSFE']->sys_language_content;
//          $languageCondition = '(sys_language_uid IN (-1,' . $currentLanguage . ')';
            $languageCondition = '(sys_language_uid IN (-1,0)';
//          if (0 < $currentLanguage) {
//              if (TRUE === $hideUntranslated) {
//                  $languageCondition .= ' AND l18n_parent > 0';
//              }
//              $nestedQuery = $GLOBALS['TYPO3_DB']->SELECTquery('l18n_parent', 'tt_content', 'sys_language_uid = ' .
//                  $currentLanguage . $GLOBALS['TSFE']->cObj->enableFields('tt_content'));
//              $languageCondition .= ' AND uid NOT IN (' . $nestedQuery . ')';
//          }
```

Thanks for considering this input. :-)

**Comment by NamelessCoder** [comment]
Hi Stefan,

Thanks for reporting!

If there is an issue with this we would like the fix included in VHS 2.3 which is due to be released soon (estimate a couple of weeks, max). But before that I do have a few questions:

* Do other code places in the class also need to be modified?
* Does this mean that the `hideUntranslated` argument should be deprecated and handled some other way?
* Are we required to manually support the `config.*` options for translation handling?
* Is it safe to remove the `enableFields` clauses? The article you link to seems to insist on it.
* Should `$currentLanguage` not still be used in a nested condition, e.g. "if ((lang in -1,0) || (lang = current and lang-parent eq 0))"? (excuse the pseudo).

If you have the answers/solutions for those then we would definitely appreciate a pull request which corrects the behaviour while taking the questions above into consideration.

**Comment by mrk131324** [comment]
Actually this issues is of more generell nature.

v:content view helpers should behave exactly as TS cObject CONTENT and RECORD when it come to language and translation handling. Right now it does not support languageMode = contentFallback.

The whole AbstractContentViewHelper->getContentRecords method mimics the behavior of CONTENT. Why don't you simply use CONTENT instead? Usage of this ViewHelper in BE-Mode is excluded anyway, so there is no reason not to use the TSFE and TS cObjects.

**Comment by NamelessCoder** [comment]
@mrk131324 I'm not sure how using CONTENT/RECORD on ContentObjectRenderer can be made to fit the case of `v:content.get` (e.g. returning unrendered records). But I would certainly appreciate a pull request with a suggestion how it might work - because I agree we should "do what the core does" and that CONTENT/RECORD would be an easy way to do that, assuming it fits our cases.

**Comment by mrk131324** [comment]
I'll try to see into it. But I cannot say when.

But how about just copy and adjust

typo3/sysext/frontend/Classes/ContentObject/ContentContentObject.php->render()?

**Comment by NamelessCoder** [comment]
Related issue https://github.com/FluidTYPO3/vhs/issues/774

**Comment by dmitryd** [comment]
There are other problems with the current approach:
* If any field in the $TCA has l10n_mode=exclude, you will not find values for it in the translated record. Thus what you fetch there, is incomplete and can miss values completely.
* As a result of the previous point, starttime/endtime from the main language do not work anymore in translated records, thought they work in "standard" TYPO3.

The fix here would be to collect l18n_parent values from fetched records, fetch records by uid from tt_content and do proper overlays. Something like:

```php
	protected function fetchRowsWithOverlay(array $rows, $language) {
		$uidList = array();

		foreach ($rows as $row) {
			$uidList[] = $row['l18n_parent'];
		}
		$rows = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows('*', 'tt_content',
			'uid IN (' . implode(',', $uidList) . ')' . $GLOBALS['TSFE']->sys_page->enableFields('tt_content'),
			'', 'sorting'
		);
		foreach ($rows as &$row) {
			$row = $GLOBALS['TSFE']->sys_page->getRecordOverlay('tt_content', $row, $language, $GLOBALS['TSFE']->sys_language_contentOL);
		}

		return $rows;
	}
```

I have no code for the current version of EXT;vhs but for one of previous versions it would look like:

```diff
diff --git a/www/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php b/www/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php
index 917fde5..ca6d00a 100644
--- a/www/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php
+++ b/www/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php
@@ -165,6 +165,9 @@ abstract class Tx_Vhs_ViewHelpers_Content_AbstractContentViewHelper extends \TYP
                                        ' AND ' . $languageCondition;
                        }
                        $rows = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows('*', 'tt_content', $conditions, 'uid', $order, $limit);
+                 if ($currentLanguage != 0) {
+                         $rows = $this->fetchRowsWithOverlay($rows, $currentLanguage);
+                 }
                        if (TRUE === (boolean) $this->arguments['render'] && FALSE === empty($rows)) {
                                $content = $this->getRenderedRecords($rows);
                        } else {
```

This is not very optimal because there are too many database queries (localized -> main -> localized). May be you can optimized it. The general idea is that you always need to get the main language record and overlay the translated record on it.

**Comment by NamelessCoder** [comment]
Thanks a lot for the detailed analysis Dmitry, much appreciated! We will start off with the most costly solution of (re-)applying overlays exactly as in your example and optimise later, if needed/requested.

**Comment by Sengchheang** [comment]
Similar issue here and I am using ext:vhs 2.4.0 and T3 7.6.4.
I have summarised all above changes into a single commit - https://github.com/Sengchheang/vhs/commit/d0a0dafe7c931c7b35d653ca0a7f04d973395f8d to try out if the changes can resolve this issue.

Unfortunately the fallback is not working properly (happening in **v:content.render**) due to `$GLOBALS['TSFE']->cObj->cObjGetSingle('RECORDS', $conf);` used in function of ext:vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php

```
protected function renderRecord(array $row) {
		if (0 < $GLOBALS['TSFE']->recordRegister['tt_content:' . $row['uid']]) {
			return NULL;
		}
		$conf = array(
			'tables' => 'tt_content',
			'source' => $row['did'],
			'dontCheckPid' => 1
		);
		$parent = $GLOBALS['TSFE']->currentRecord;
		// If the currentRecord is set, we register, that this record has invoked this function.
		// It's should not be allowed to do this again then!!
		if (FALSE === empty($parent)) {
			++$GLOBALS['TSFE']->recordRegister[$parent];
		}
		$html = $GLOBALS['TSFE']->cObj->cObjGetSingle('RECORDS', $conf);

		$GLOBALS['TSFE']->currentRecord = $parent;
		if (FALSE === empty($parent)) {
			--$GLOBALS['TSFE']->recordRegister[$parent];
		}
		return $html;
	}
```
Maybe the issue is actually not here but https://review.typo3.org/#/c/14464/7

Some hints for workaround will definitely help a lot.

**Comment by danielkestler** [comment]
My two cents to this (and related) issues: In my opinion, the viewhelpers accessing content elements are fundamentally flawed and need to be rewritten. They are just to far off from the core and lead to errors in workspaces and translation overlays.

I am currently considering how this could be solved better (and more core-like, not doing any custom SQL queries ...), perhaps with some restrictions in the feature set. Sorry that I have no solution here yet and just complain ... :-/

**Comment by NamelessCoder** [comment]
I agree we need to rework these, along the lines of what @bjo3rnf did to the menu ViewHelpers. Any takes on that would be very welcome!
