### ISSUE TITLE
TYPO3\\CMS\\Core\\SingletonInterface not found in Typo3 4.5 (VHS 1.8.5)

### ISSUE THREAD

**Issue by wolffc** [FluidTYPO3/vhs#777]
hi i Have a Typo3 4.5 instllation and have updated to VHS to version 1.8.5 this causes the error below:
```
PHP Fatal error:  Interface 'TYPO3\\CMS\\Core\\SingletonInterface' not found in /var/www/aerticket_2012070601/typo3conf/ext/vhs/Classes/Service/AssetService.php on line 36, referer: https://extranet.aerticket.de/de/aktuelles/
```
switching back to vhs 1.8.4 removes the error. so it seems this error has been introduce in version 1.8.5 of vhs

**Comment by cedricziel** [comment]
Confirmed. The problem is namespaces sneaked into the tag which should have been in the 2.x branch.

**Comment by NamelessCoder** [comment]
Yep, unfortunately this one is correct - but there is nothing we can do to solve it. The `1.8.4` version of VHS is the very last one capable of running on TYPO3 4.x. So stick with that until you go 6.2 ;)

**Comment by wolffc** [comment]
yes. but version 1.8.5 Advertises in TER to be 4.5 compatible which is bad.

**Comment by NamelessCoder** [comment]
True, of course - it is a mistake but our problem is that we can't replace already uploaded TER versions :/

**Comment by wolffc** [comment]
what about re-releasing the 1.8.4 as 1.8.6 ?

**Comment by NamelessCoder** [comment]
Hi Christian - sorry about the delay!

Sadly re-releasing isn't an option either. It would require us to separate that into a branch and tag that, after which the branch could never be touched (tags being permanent and all) - and perhaps worse, would register that version on TER as the latest one released.

I am sincerely sorry about the fatal errors. I'm the one responsible for the incorrect dependencies being recorded - but solving this problem by way of tags introduces significant disturbances and applies to a product that's EOL, so I respectfully decline that option.

There is one thing that might at least help a little, but I don't know if that's even possible. If @Avalarion wouldn't mind chipping in here that would be great. Maybe the TER database can be manipulated to correct the minimum version dependency for VHS 1.8.5 to TYPO3 6.2 (because it is current LTS). Still not the perfect solution but it might hide the problem from TER users. Let's see!
