### ISSUE TITLE
v:page.header.meta renders tag with contents

### ISSUE THREAD

**Issue by aksenovaa** [FluidTYPO3/vhs#790]
If I use <v:page.header.meta name="viewport" content="width=device-width, initial-scale=1.0"/> or
{v:page.header.meta(name: 'viewport', content: 'width=device-width, initial-scale=1.0')}

Then the output to the page I get:
<meta name="viewport" content="width=device-width, initial-scale=1.0">width=device-width, initial-scale=1.0</meta>
instead of
<meta name="viewport" content="width=device-width, initial-scale=1.0" ./>

TYPO3 v 7.1

**Comment by typo3ua** [comment]
I have the same. I update VHS to version 2.3.1 ... TYPO3 v 6.2.10
My code:
~~~
<v:page.header.meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
~~~
Output:
~~~
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no</meta>
~~~

**Comment by rabe69** [comment]
Can confirm this bug.
The problem seems to come from the changes in MetaViewHelper.php
If I change line 57 from this:
$GLOBALS['TSFE']->getPageRenderer()->addMetaTag($this->renderTag($this->tagName, $this->arguments['content']));
to this:
$GLOBALS['TSFE']->getPageRenderer()->addMetaTag($this->renderTag($this->tagName));
The output is correct.

**Comment by mhmli** [comment]
Same here. Same problem, same solution.
