### ISSUE TITLE
v:page.menu: class of submenu wrapper 

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/vhs#792]
I want to achieve a markup like this:

    <ul class="nav">
      <li>
        <a href="#">Lorem</a>
        <ul class="lvl-1">
          <li><a href="#">Ipsum</a></li>
        </ul>
      </li>
    </ul>

But `<v:page.menu class="nav">` adds the `nav` class to all the `ul` elements. I found no possibility to reconfigure the class name for the submenu levels.

**Comment by cedricziel** [comment]
This is only possible when you render the first level manually.

Something like this:

```xml
<nav>
    <v:page.menu class="nav">
        <f:for each="{menu}" as="item">
            <f:link.page pageUid="{item.uid}" title="{item.linktext}">{item.linktext}</f:link.page>
            <f:if condition="{item.hasSubPages}">
                <!-- Of course you could also just use v:page.menu. -->
                <v:page.menu.sub pageUid="{item.uid}" />
            </f:if>
        </f:for>
    </v:page.menu>
</nav>
```

I think the options you set on the ``v:page.menu`` ViewHelper are available as properties on the ``{item}`` object. You should be able to inspect them with ``{item -> f:debug()}`` of course.

If you you feel the pressing need to add such setting to the viewhelper itself, feel free to PR.

I hope that helps-otherwise feel free to followup on that topic :)

PS: @bjo3rnf has some good posts about ``EXT:vhs`` in particualar and FluidTYPO3 in general in his blog https://worksonmymachine.org . There's also at least two posts on menu rendering (https://worksonmymachine.org/blog/a-guide-to-menu-rendering-with-fluidtypo3 , https://worksonmymachine.org/blog/menu-rendering-in-fluidtypo3-revisited)
