### ISSUE TITLE
[FEATURE] Async loading for JS

### ISSUE THREAD

**Issue by Madii** [FluidTYPO3/vhs#797]
In Typo3 7.1 async loading of JS was introduced. It would be nice to have it  ... I already tried myself to implement it but before i do a pull request maybe someone looks over it ;-) 
-> https://github.com/Madii/vhs/commit/c9d2528de114ab6a90ad16268412ef6d1e89b928

**Comment by ste101** [comment]
You could also add 'defer' as attribute.

**Comment by bjo3rnf** [comment]
Hi @Madii, 

where is the setting ``async`` actually evaluated and applied to the resulting tag? Sorry for maybe being blind but I can't see that. And what are your changes to the unit test aiming at?

Cheers
Björn

**Comment by bjo3rnf** [comment]
Hi @Madii,

any news on this PR?

Cheers
Björn

**Comment by Madii** [comment]
Sry for late response ;-) ...was too busy with work this month. I give you soon an update on this PR. Have to look over it again to answer your question.

**Comment by Madii** [comment]
Ok...you are not blind. I had just forgotten to implement the setting in the service. Doing it. The unit test is just aiming for the type of async. If it is boolean

**Comment by NamelessCoder** [comment]
This will be incompatible with merged files, must only work for JS and must only be respected if standalone is TRUE and asset is using `path` instead of `content`. This has to be documented as well; and not just on the ViewHelper argument but on the property of the Asset object too.

On a side note, these restrictions and pitfalls are exactly why this feature along with conditional wrapping has not been implemented in VHS... it's so specific and isolated in use case that it's barely useful, imho. The idea itself is fine but the perspective for implementing it in VHS is just too sketchy.

**Comment by xf-** [comment]
Coordinating all features and provide a simple usage will be hard like NamelessCoder wrote.

If you provide a solution for all situations and possible development options, your PR is welcome.
If you provide a PR include UnitTest cases for all possible options. We don't want to remove a merged feature the next day, because it causes problems in complex situations.
I will close this until a PR.

Additionally, you can use page.header and put in it what you want.
