### ISSUE TITLE
[RFC][FEATURE] Wraps for Assets

### ISSUE THREAD

**Issue by cedricziel** [FluidTYPO3/vhs#807]
I think we need wraps for Assets. - The one or the other way. TS Conditions suck for conditional stylesheets for example.

Because the rewrite of the asset part didnt happen at all (my fault _ducksandruns_), we need to take this a bit further.

In my opinion we need wraps for:

* [ ] groups
* [ ] header parts
* [ ] footer parts

Can you please suggest places where you think this would make sense and share general thoughts? Technical details apart please :)

ping: @outdoorsman @NamelessCoder @bjo3rnf

**Comment by NamelessCoder** [comment]
I'm all for supporting a wrapping of sorts, but I absolutely think we should be separating this to a new extension first. And if I am not mistaken, such features would be supported by for example Assetic?

I would do this as follows:

* Create the new extension and adopt the ViewHelpers and their parameter namings, but have them create Assetic objects/config instead.
* Create in this new extension a temporary API that will consume VHS asset objects.

This will allow us to properly deprecate the asset feature of VHS giving it however long is required. The benefit here is that any features we create _after_ this point will be created in the proper way in the proper extension - if we don't, we simply add to the pile of features we have to replicate in or delegate to whatever asset handling dependency we introduce.

And we'd like to do less, not more. IMHO the ideal way to achieve that is to delegate to a third-party dependency (one that's considered a standard). This extension becomes a wrapper for the third-party dependency and VHS becomes a wrapper for this extension; either through an actual dependency or a silent one with some friendly messaging, because the VHS wrapper technically becomes deprecated immediately.

**Comment by BenjaminBeck** [comment]
+1 for using Assetic
And there is one thing that recently happened to me:
I added some css with v:asset.style inside a content element that is not present on every page.
The behaviour here was, that this style was merged with the main stylesheet and created a completely new file (which broke caching..). Maybe this -default behaviour- can be improved?

**Comment by cedricziel** [comment]
I would like to give up on this, as I consider a clean asset pipe decoupled from the cms state of the art.

Let me know what you think.

**Comment by bjo3rnf** [comment]
https://youtu.be/OTLoEr21raA

**Comment by NamelessCoder** [comment]
Drop it like it's hot ;)

**Comment by cedricziel** [comment]
Rocked to the bottom :)
