### ISSUE TITLE
View helper instances should not be recycled in page.menu.sub rendering

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/vhs#846]
If I have a simple menu like this:
```xml
<v:page.menu>
 <ul>
  <f:for each="{menu}" as="item">
   <v:tag name="li" class="{f:if(condition: item.hasSubPages, then: 'hassub')}">
    {item.linktext}
    <v:page.menu.sub pageUid="{item.uid}" />
   </v:tag>
  </f:for>
 </ul>
</v:page.menu>
```
then contrary to expectations, the `class` argument of the `li` elements will not be correctly set. The reason is a bit complicated: For the first menu level, the tag view helper gets rendered for an item and calls `renderChildren()`. This invokes page.menu.sub, which wraps back to rendering the parent menu view helper again with different items. For any items in the submenu, `renderChildren()` is again called on the tag view helper. The problem is: This will be the _exact same_ view helper, i.e. the same object instance. The `class` argument of the tag view helper that is still in `renderChildren()` at the first menu level gets overwritten and is never restored. When the call finally returns and `renderTag()` is called, the `class` still has the value from the submenu.

The correct fix would be to always use fresh view helper instances when rendering sub menus, but I'm not sure whether that is possible with fluid. This particular example could also be fixed by saving the `class` argument in TagViewHelper before calling `renderChildren()`, but that's of course not a general solution.

**Comment by NamelessCoder** [comment]
You've encountered one of the most complex situations you possibly could, in Fluid. The shortest possible back story: class instance reuse (ViewHelpers are essentially, undocumented and unannounced Singletons) was implemented as a performance optimisation measure, which in turn was necessary because of the rather costly logic that is associated with class instancing in TYPO3 (and Flow). Rather than construct new instances, workarounds were implemented to keep an uninitialised instance at hand for some operations, use `clone` for others and finally use compiled (static, closure) rendering for other cases. This has ties to pretty much every ViewHelper operation in Fluid - in both the parser and the compiler.

This puzzle is one that is quite difficult to solve. Take my word for it or check the standalone Fluid extension which removed this (but now is scheduled for another assortment of performance enhancements that help with limiting new instances, among other things.

The future perspective is fortunately much brighter:

I'm working on integrating the standalone Fluid engine back into CMS which will be the ideal time to handle these edge cases. I'm still not 100% sure *how* exactly, but this issue will either be removed or turned into a controllable feature (interface, for example) to indicate to Fluid when/if to allow reusing instances. At the current time there is no solution, but quite soon the solution will either come automatically or be extremely easy to implement in those ViewHelpers that would require it ;)

**Comment by pkerling** [comment]
Thanks for the detailed write-up! I'll just have to wait then... (and use my patched copy of TagViewHelper in the meantime)
