### ISSUE TITLE
Exception when using render.uncache while serialization

### ISSUE THREAD

**Issue by p2media** [FluidTYPO3/vhs#852]
We want to display a Plugin which should not be cached because of session data but we are getting an Exception (`Serialization of 'Closure' is not allowed`) while serialization.

In the first Browser it works like charm.
But if we call the same page in another Browser we get an Exception when the ViewHelper tries to serialize the Template.

Here is our Code:

View:
```
{namespace v=FluidTYPO3\Vhs\ViewHelpers}

<v:render.uncache
    partial="User/Data"
    arguments="{
        uid: '{uid}'
    }"
/>
```

`User/Data` Partial:
```
{namespace v=FluidTYPO3\Vhs\ViewHelpers}

<v:render.request
	action="displayUserData"
	controller="User"
	pluginName="..."
	extensionName="..."
	vendorName="..."
	arguments="{
		uid: '{uid}'
	}"
/>
```

We are using `TYPO3 6.2.12` and `vhs 2.3.3` (TER)

We found that an other (german) developer had the same issue:
https://forum.typo3.org/index.php/t/207648/-lt-v-render-uncache-partial-gt-ignoriert-extension-settings

**Comment by p2media** [comment]
For now we are using an ugly workaround:
We defined a Marker in our View and used `stdWrap.postUserFuncInt`.

**Comment by xf-** [comment]
sounds like typical T3 issue and lock.
Depends a little bit on system and how long the lock lasts.
The lock is important, uncache big parts are a bad idea.

I think we can't really improve this.
@NamelessCoder what do you think?

**Comment by NamelessCoder** [comment]
The issue here is not so much the rendering process; it is the serialisation of **arguments** that you pass to the template. If you avoid passing complex arguments this will work - and by complex argument, really, any DomainObject is pretty much implied as unserialisable. You can manipulate your domain objects' classes to make sure properties are serialisable but the better way is to not provide complex arguments.

Instead, you should rely on very simple values like an integer to identify an object, an array of integers to identify multiple objects, a table/field name to retrieve relational objects etc. - and then, in the controller belonging to the request you render, or in the template associated with it, "thaw" these scalar values to create the object instances you require.

Think of these "arguments" for `v:render.request` as URL parameters. Any value that wouldn't be possible to transfer in an URL is likely not possible to transfer to `v:render.request`. I'm afraid there's no automated way around this - the only solution (workaround) is to be very careful about what you pass.

**Comment by NamelessCoder** [comment]
Oh and by the way: when you do `{uid: '{uid}'}` instead of just `{uid: uid}` you are actually creating an additional TextNode which contains the ObjectAccessorNode you really want. Avoid passing variables this way - use the direct ObjectAccessor way in my example and you should be serialising scalar values instead of object instances.

**Comment by ducatisti-bln** [comment]
I have the same problem. Maybe anyone has a idea/solution?
In a template i call
`<v:render.uncache partial="Event/EventPriceDropDown" arguments="{ price: '10' }" />`
and call the page on frontend with this Exception

> Serialization of 'Closure' is not allowed
Exception thrown in file
/var/www/vhosts/XXX/XXX/typo3_src-7.6.16/typo3/sysext/core/Classes/Cache/Frontend/VariableFrontend.php in line 85.
