### ISSUE TITLE
v:render.uncache requires "partial"

### ISSUE THREAD

**Issue by mabolek** [FluidTYPO3/vhs#855]
Hi!

I noticed the following difference between Fluid and VHS:

When using Fluid's core render view helper (e.g. "<f:render ...>") filling out partial="foo/bar" is not required if you are rendering a section within the same file.

When using v:render.uncache, specifying partial is required. I.e. you cannot render content within the same file if it is a flux template, and you have to repeat the name of the file you are working in, reducing portability.

- Mathias

**Comment by featdd** [comment]
I'm guessing It has to to with the INTincScript postuserfunc which is used to render the partial uncached.
The partial argument could be necessary to determine a template path because without there is no template context to find the given section, but I'm not 100% sure...

**Comment by NamelessCoder** [comment]
I was just about to comment exactly what @featdd just commented. We create an instruction to render a specific partial, optionally a section from that partial. The main issue is that we can't resolve the name of the current template (which could be a template, a partial or a layout) and as such we unfortunately must require the `partial` argument. The `section` argument is optional because the delegated, uncached rendering does not care if it was passed - it will just pass it along to the Fluid view base class since NULL is the default value anyway.
