### ISSUE TITLE
cObj in v:render.uncached rendered partial undefined

### ISSUE THREAD

**Issue by fgerards** [FluidTYPO3/vhs#914]
Hi,

using the v:render.uncached for a partial and assigning _all parent-view arguments to it leaves the cObj in the rendered UncachedTemplateView empty.

Thus, operations like {myObject.content -> f:format.crop ... throw a fatal error.

I guess there is sth wrong with configuring the $GLOBALS['TSFE']->config['INTincScript'] and assigning the serialized fresh templateView to it ?

**Comment by NamelessCoder** [comment]
Hi Frank,

Although I'm not sure if this is documented, the way that `arguments` are handled on this deferred rendering is that they're serialized in order to store them in an USER_INT configuration. That also means that there are some data types that are not supported; namely stuff like huge objects, closures, etc.

There's no other way for us to store these variables so we are limited by this in all cases.

There is only one way to avoid this and that's to avoid passing the entire object in arguments. This also means that in some cases you may even need to create a custom ViewHelper that (just as an example) can load a cObj instance by content element UID, so you can pass just the UID to your uncached template and have that template "reload" the object itself. But in most cases you should be able to pass only specific variables instead of `_all` and unless your variables contain a Closure, it should "just work" - cObj however may be an exception because of the huge size and many, many dependencies.

Hope that made sense - if not, feel free to ask further ;)
