### ISSUE TITLE
<v:asset> viewhelper is not using markers position like HEADERDATA or FOOTERDATA

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/vhs#930]
I though that using the flag `allowMoveToFooter` it would move that part of script somewhere in `HEADERDATA` or in `FOOTERDATA`, but it seems that it's not working like this way.

Why? This fucks up all the logic of scripts and style management coming from extensions.

Is it possible to be fixed?

---

This is an example of `PageRenderer.html` customized to move all the scripts on bottom based on some logic:

```html
###XMLPROLOG_DOCTYPE###
###HTMLTAG###
###HEADTAG###

###METACHARSET###
###INLINECOMMENT###

###BASEURL###
###SHORTCUT###
###TITLE###
###META###

###CSS_LIBS###
###CSS_INCLUDE###
###CSS_INLINE###

###HEADERDATA###
<!--###POSTJSMARKER###-->
</head>
###BODY###
###FOOTERDATA### <!-- Here I want all the VHS standalone with allowMoveToFooter=1 -->
###JS_LIBS### <!-- From now on will live extension injected through typoscript page.include... -->
###JS_INCLUDE###
###JS_INLINE###
###JS_LIBS_FOOTER###
###JS_INCLUDE_FOOTER###
###JS_INLINE_FOOTER###
</body>
</html>
```
and it could work only if VHS assets were injected based on marker position.

**Comment by NamelessCoder** [comment]
> I though that using the flag allowMoveToFooter it would move that part of script somewhere in HEADERDATA or in FOOTERDATA, but it seems that it's not working like this way.

First: `allowMoveToFooter` is deprecated, use `movable` instead.

Second: no, that's not what that flag does. All it does is allow the asset to be placed in the footer *if TYPO3 is configured to place assets in the footer*. That's why the flag isn't called *moveToFooter* or *move* and uses the prefix `allow`.

> Why? This fucks up all the logic of scripts and style management coming from extensions.

VHS assets will *always* come last. *Always*. You can control the inclusion order of individual VHS assets using the `dependencies` property but *you cannot control the inclusion order of non-VHS assets by manipulating VHS assets*.

VHS aimed specifically to not override any templates (which includes the PageRenderer). VHS is a ViewHelper collection that doesn't make design decisions for you.

> Is it possible to be fixed?

I honestly don't think so. We're not going to accept a replacement PageRenderer.html file and a toggle to switch the behavior (from DOM manipulation to marker usage) seems to be so slim an edge case that for the two-three years VHS Assets have existed, you're the very first person to request it.

**Comment by julianxhokaxhiu** [comment]
> First: allowMoveToFooter is deprecated, use movable instead.
I tryed but that end up with an error that `movable` is not declared ( see #829 ) and it's still like that in latest TER version ( at least on 6.2 LTS )

> I honestly don't think so. We're not going to accept a replacement PageRenderer.html file and a toggle to switch the behavior (from DOM manipulation to marker usage) seems to be so slim an edge case that for the two-three years VHS Assets have existed, you're the very first person to request it.

That `PageRenderer.html` is an example I did override ( but I'm not expecting that to come from VHS ) in Typoscript and it's quite easy to do. What I'm really asking here is if that's a possibility to specify in a flag like `position="headerData"` which will inject your asset content in `page.headerData` for example.

As I see in the code you're just actually searching for '</head>' and '</body>' to find and replace that part and inject it. But that's it not always the case. It actually sound strange to me that I'm really the first one asking for that, but it should be really normal that I want a structure of resources defined like:
- HEAD : `<title>`, `<meta>`, `<link>`
- PRE-ENDBODY : `<script>`

And that's a normal suggestion that comes from Google Pagespeed and ANY website in the earth actually has this structure. What I am trying to accomplish is understanding where Typo3 is injecting stuff and now that I figured it out, I see that your extension is doing an asset management OUT of the logic of typo3, which makes that really bad honestly, because you cannot predict where it's gonna be ( before all extensions script? after? in the middle? ).
I know I can use dependency but that means there everywhere in the project, any extension that I install is using your ViewHelpers, which is totally not the case ( Powermail, Formhandler, etc. for example ).

So, I'll reformulate my question by asking: is it possible to have a flag `position` ) so I know that particular content will be injected there?

Thanks in advance

**Comment by NamelessCoder** [comment]
> I tryed but that end up with an error that movable is not declared ( see #829 ) and it's still like that in latest TER version ( at least on 6.2 LTS )

Make sure you use the documentation for the appropriate version ;) I guess you were reading the references for the `development` branch and should have used `master` or the specific version.

Before we discuss further, please read the (currently unavailable) whitepaper on why VHS Assets exist in the first place. You can read that here: http://web.archive.org/web/20130701023808/http://fedext.net/articles/assets-in-fluid.html

Since writing that article *some* of the information is no longer correct - for example, PageRenderer has become more reliable so the issues with cached/uncached content no longer exists. The main reasons you should focus on are those related to the dependency ordering of scripts and the aspects of reduced control (fire-and-forget nature) of all current core methods of attaching assets. Those explain why VHS assets do not use the native methods.

In addition to that, there is the consideration that VHS assets are compiled after everything on the page has been rendered; the logic sequence makes it impossible to include assets using PageRenderer at this point (PageRenderer is already done rendering everything). This allows code at any point in the process to isolate and manipulate any asset or asset group, but naturally it means we can't use any of the existing methods.

But before we continue you should read the whitepaper and check out how VHS actually renders its assets. I've tried to push for a similar strategy in TYPO3 assets themselves (e.g. Assetic with a ViewHelper and TypoScript API), but it appears to be a *very* low priority concern.

**Comment by bjo3rnf** [comment]
Closed due to a lack of response. Please reopen for further discussion if required.

**Comment by julianxhokaxhiu** [comment]
Sorry @bjo3rnf I forgot to update this ticket because in the meantime I didn't work precisely on this part personally. Although I still find that the view helper is doing a find and replace on `</head>` and on `</body>`, using extensions like `scriptmerger` you can practically forget where the scripts are. Although I'm using the pattern of "all the CSS on header" and "all the JS on footer", I'm still using the `PageRenderer.html` way to move them to the right order.

I hope that maybe meanwhile you'll find a way to optimize this whole pattern by providing an out-of-the-box experience that just works.

Personally I'll quit the typo3 scene in the next months, so I'm just sad that I'll not be able to follow these thngs anymore :)

**Comment by bjo3rnf** [comment]
No worries @julianxhokaxhiu and thanks for your feedback.
