### ISSUE TITLE
Fluid rendered standalone v:asset.script (with standalone="TRUE" fluid="TRUE") not caching

### ISSUE THREAD

**Issue by shr3k** [FluidTYPO3/vhs#931]
vhs 2.3.3 under 6.2 LTS, same content gets saved repeately under different names like:
```
/typo3temp# md5sum vhs-assets-goapp-*
7e24bac0c38db33a526ad630bd5ea43b  vhs-assets-goapp-106871f9fc1996f37b1b72ba5848595a.js
7e24bac0c38db33a526ad630bd5ea43b  vhs-assets-goapp-2778748e212d8aa133a7b52616f64ca7.js
7e24bac0c38db33a526ad630bd5ea43b  vhs-assets-goapp-72836eceec947cdd8722139209ed990d.js
```
Fluid rendered JavaScript:
```
Ext.onReady(function() {
    Ext.QuickTips.init();
    Heron.App.create();
<f:security.ifAuthenticated>
<f:then>
    var sessionTask = {
        run: function() {
            Ext.Ajax.request({
                url: '/couchdb/_session',
                success: function (response) {
                    GObec.project.session = Ext.decode(response.responseText);
                }
            });
        },
        interval: 60000
    };
    Ext.TaskMgr.start(sessionTask);
</f:then>
<f:else>
    Ext.Ajax.request({
        url: '/couchdb/_session',
        success: function (response) {
            GObec.project.session = Ext.decode(response.responseText);
        }
    });
</f:else>
</f:security.ifAuthenticated>
    (function() {
        var hideMask = function () {
            Ext.get('loading').remove();
            Ext.fly('loading-mask').fadeOut({
                remove: true
            });
        };
        hideMask.defer(250);
    }).defer(500);
});
```

**Comment by NamelessCoder** [comment]
Hi Martin,

You're using `v:security` which is intentionally impossible to cache when a user *is* logged in (doing so would cache protected template code in your example). This results in a new checksum suffix in every request which triggers the code that writes the asset. Note that there are quite a lot of context-based condition ViewHelpers that will also do this.

In your case you may want to consider `v:render.uncache` to generate a tiny `USER_INT` object that renders a Partial which puts this script *inline* in the response body. That way you can have a static asset that you *extend* whenever a user is logged in, or whichever condition you like. Hint: if you want the rendering that goes on in the uncached bits to use conditions, put them in the Partial - not around the `v:render.uncache` block.

**Comment by shr3k** [comment]
Hi Claus, thanks for the explanation, I'm trying to somehow throw away fed:coffee and start using v:asset.script. Script generating with fed:coffee and caching in typo3temp worked just fine (different users, various domain objects).

**Comment by NamelessCoder** [comment]
That's a blast from the past :) you can kind of get the result you want if you pass things like the user UID or group UID as the only variable to your Fluid asset. Doing that makes the checksum unique for each user but obviously makes the asset name completely predictable which could become a nice, fat security hole. That's why I didn't suggest it. It *is* a valid solution if your assets aren't sensitive as such and you take the necessary precautions to protect the server-side stuff that the asset's logic calls, but I wouldn't recommend it. Clean separation is always safer ;)

**Comment by shr3k** [comment]
Yep that was pretty bad example. I'm using it more or less to reduce the delivered JS code plus there are some very old pieces of JS code - nothing to do with user security. Anyway I figured out interesting thing:
This example caches in typo3temp very well (depending on json variables):
```
{project.projectCadastres -> v:format.json.encode() -> v:variable.set(name: 'cadastresJson')}
{project.projectDistricts -> v:format.json.encode() -> v:variable.set(name: 'districtsJson')}
<v:asset.script path="..." standalone="TRUE" fluid="TRUE" variables="{cadastresJson: cadastresJson, districtsJson: districtsJson}" />
```
But forwarding one or more ObjectStorageprototype  results in generating new and new scripts:
```
<v:asset.script path="..." standalone="TRUE" fluid="TRUE" variables="{cadastres: project.projectCadastres, districts: project.projectDistricts}" />
```
Are there any restrictions regarding variable types in checksum counting?

**Comment by NamelessCoder** [comment]
Specifically about ObjectStorage, it uses `spl_object_has` as keys and naturally these IDs are unique for every single instance. Since ObjectStorage has no fixed ID (like every entity does) this results in new checksums every time. It's not exactly a restriction, it's just expected behavior given the input types. It's a bit of a challenge to create something that is sufficiently strict to be predictable and at the same time flexible enough to allow these dubious types.

Now, had ObjectStorage for example used the `table:uid` format as keys for already persisted objects, at least you would have been able to use it this way when all members are persisted. But it doesn't. And you can't replace ObjectStorage. Defeat.

The only way to make sure this works in a predictable way is to correctly extract every single dubious variable to something 100% consistent. Usually that means creating a new array of variables, e.g. `variables="{name: user.name, email: user.email}"` so you don't pass any objects whatsoever.

**Comment by shr3k** [comment]
Wow, it explains a lot, thanx for all the helpful info. It would be great to add these notes to the help for others who's maybe interested in templating with vhs and they don't know much, what's under the hood of Extbase. Like me. :)
