### ISSUE TITLE
Enable usage with typo3fluid/fluid standalone

### ISSUE THREAD

**Issue by 7elix** [FluidTYPO3/vhs#968]
Allow usage of vhs Viewhelpers with stand alone Fluid #yay
Resolve TYPO3 dependencies

:)

**Comment by NamelessCoder** [comment]
![](http://i.imgur.com/sWpXz2D.jpg)

**Comment by 7elix** [comment]
… hope, my idea/wish did not send the wrong message …

**Comment by NamelessCoder** [comment]
Hehe no, it's already in the plans ;)

**Comment by NamelessCoder** [comment]
In case you're interested, the plan is:

1. Merge https://github.com/TYPO3Fluid/Fluid/pull/38 to make namespace extension a general feature.
2. Add a method to extend the namespace from within individual templates.
3. Add some of the most generic ViewHelpers from VHS in standalone Fluid itself.
4. Create a new composer package with the remaining generic ViewHelpers from VHS.
5. Move detection method to "get all ViewHelper classes in namespace" into Fluid itself, as a prerequisite for generating schemas based on two or more packages.

Items 3 to 5 can be done in any order. When done we will be in a situation where VHS on TYPO3 8.0 will "just work"; pulling in the composer dependency from step 4 and transparently adding those to the VHS namespace. TYPO3 7.6 LTS will **probably** require the override adapter extension discussed in https://review.typo3.org/#/c/44512/, I'm not entirely sure yet if there may be another way. If there is no other way than requiring said extension, we would have to **very** carefully consider how safe it would be for VHS to declare the override adapter extension as a true dependency - and thus finally enable us to actually remove the ViewHelpers that are either in standalone Fluid or the composer package of ViewHelpers.

Because it means duplicating so many ViewHelpers from VHS into other packages without being able to remove them from VHS at first, this may be a somewhat long term perspective. The shorter the period of double maintenance can be made, the better. So I think we will be solving this one in smaller pieces, first focusing on merging standalone Fluid into TYPO3 and making the override adapter perfectly safe to use. Since having those pieces done and trustworthy means the porting of ViewHelpers is then pretty much a refactoring task. It's not laziness, it's just efficiency ;)

That's just to explain why you may not see a lot of this migration happening until those seemingly unrelated tasks are done.

As always: if you wish to offer your help for this task I'd be very happy include you! Let me know if you're interested!

**Comment by NamelessCoder** [comment]
Will close this issue since we are inevitably going down this road and don't need an open reminder - we're a few steps closer than when I wrote the above in December, but not all the way there yet. The invitation to be included in this migration is still open even if this issue isn't ;)
