### ISSUE TITLE
Fatal Error in TYPO3 6.2.18 with VHS 2.4.0 from v:page.languageMenu

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/vhs#992]
Hi,

after updating TPYO3 from a former 6.x version to 6.2.18 I get an fatal PHP-Error: Fatal error: Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render() in /html/typo3/typo3conf/ext/vhs/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php on line 211

It depends on the option layout="flag", if I change it to layout="name" there are no more problems. It might be caused by the new different icon-stuff-location in the newer TYPO3 versions. Is there any workaround outside CSS? I guess it could be "flagPath" but maybe it could be useful to have a correct path by default in it.

**Comment by NamelessCoder** [comment]
Hi Markus,

Since this concerns a 6.2 version which we no longer officially support, we have to reject this one. VHS 2.4.0 incorrectly allows TYPO3 6.2 - it should require TYPO3 7.6 (and the next bugfix release will fix that problem). I've created a `legacy` branch on VHS, based on 2.3.3 which was officially the last 6.2-compatible version. We are happy to receive pull requests to this branch but cannot prioritise it ourselves - you are *very* welcome to create a pull request into that branch, but please make sure that it follows the guidelines closely. Since it has such low priority, avoiding any formal errors means faster acceptance ;)

Will close this issue since we don't keep open issues concerning officially unsupported versions.
